/* eslint-disable @typescript-eslint/require-await -- fake postgres callables intentionally mirror the async driver API */
import {Buffer} from 'node:buffer';
import {describe,expect,it,vi} from 'vitest';
import {EnvironmentExportKeys,PostgresIndividualExportStore,PostgresIndividualSnapshot,canonicalIndividualRequestHash,createIndividualGateway,reauthorizeIndividual} from '../../../packages/reporting/src/index.ts';
import type {ExportActor,ExportJobMetadata,JsonObject} from '../../../packages/individual-exports/src/index.ts';

const actor:ExportActor={orgId:'22222222-2222-4222-8222-222222222222',userId:'11111111-1111-4111-8111-111111111111',roles:['senior']};
const metadata:ExportJobMetadata={id:'33333333-3333-4333-8333-333333333333',orgId:actor.orgId,subjectId:actor.userId,requestedBy:actor.userId,request:{scope:['audit'],format:'json'},selection:{orgId:actor.orgId,subjectId:actor.userId,auditResourceIds:['shared-target']},state:'ready',createdAt:'2026-09-11T00:00:00.000Z',expiresAt:'2026-09-12T00:00:00.000Z',asOf:'2026-09-11T00:00:00.000Z',sourceVersion:'snapshot-v1',plaintextBytes:10};

describe('WP-020 individual Postgres behavior',()=>{
  it('reads and counts audit rows only for the authorized subject on a shared target',async()=>{const calls:Array<{query:string;values:unknown[]}>=[];const sql=Object.assign(async(strings:TemplateStringsArray)=>strings.join('').includes('statement_timestamp() as as_of')?[{as_of:new Date('2026-09-11T00:00:00.000Z'),source_version:'snap'}]:[],{unsafe:async(query:string,values:unknown[]=[])=>{calls.push({query,values});if(query.includes("jsonb_build_object('resource_id'"))return[{payload:{id:'own-event',resource_id:'shared-target'} satisfies JsonObject}];if(query.includes('count(*)::int'))return[{count:1}];return[];},release:vi.fn()});const snapshot=await new PostgresIndividualSnapshot({reserve:()=>Promise.resolve(sql)} as never).readRepeatableReadSnapshot({actor,selection:metadata.selection,requestedTables:['audit_events']});expect(snapshot.rows.audit_events).toEqual([{id:'own-event',resource_id:'shared-target'}]);const auditCalls=calls.filter(call=>call.query.includes('audit_events'));expect(auditCalls).toHaveLength(2);for(const call of auditCalls){expect(call.query).toContain('(actor=$3 or on_behalf_of=$3)');expect(call.values).toEqual([actor.orgId,['shared-target'],`user:${actor.userId}`]);}});

  it('authorizes the frozen selection despite unrelated additions and denies a missing frozen resource',async()=>{let includeFrozen=true;const calls:Array<{query:string;values:unknown[]}>=[];const sql={unsafe:async(query:string,values:unknown[]=[])=>{calls.push({query,values});if(query.includes('from user_roles'))return[{id:'senior'}];if(query.includes('select distinct target as id'))return includeFrozen?[{id:'shared-target'}]:[];return[];}};expect(await reauthorizeIndividual(sql as never,actor,metadata)).toBe(true);const selectionCall=calls.find(call=>call.query.includes('select distinct target as id'));expect(selectionCall?.values[1]).toEqual(['shared-target']);includeFrozen=false;expect(await reauthorizeIndividual(sql as never,actor,metadata)).toBe(false);});

  it('replays durable metadata without resolving a newly expanded selection',async()=>{const request={scope:['audit'] as const,format:'json' as const};const row={id:metadata.id,org_id:metadata.orgId,subject_id:metadata.subjectId,actor_id:metadata.requestedBy,scope:metadata.request.scope,format:metadata.request.format,state:metadata.state,selection:metadata.selection,created_at:new Date(metadata.createdAt),expires_at:new Date(metadata.expiresAt),as_of:new Date(metadata.asOf!),source_version:metadata.sourceVersion!,plaintext_bytes:metadata.plaintextBytes!,failure_code:null,encryption_algorithm:null,key_version:null,nonce:null,auth_tag:null,ciphertext:null,request_hash:canonicalIndividualRequestHash(request)};const sql=Object.assign(async(strings:TemplateStringsArray)=>{const query=strings.join('');if(query.includes('from individual_report_exports'))return[row];if(query.includes('statement_timestamp() as now'))return[{now:new Date('2026-09-11T12:00:00.000Z')}];return[];},{unsafe:async()=>[],release:vi.fn()});const reauthorize=vi.fn((_sql,_actor,old:ExportJobMetadata)=>Promise.resolve(old.selection.auditResourceIds?.[0]==='shared-target'));const resolveSelection=vi.fn(()=>Promise.reject(new Error('new selection must not be resolved for replay')));const key=Buffer.alloc(32,1).toString('base64');const gateway=createIndividualGateway({client:{reserve:()=>Promise.resolve(sql)} as never,authority:{resolveSelection},snapshots:{readRepeatableReadSnapshot:vi.fn()},keys:new EnvironmentExportKeys(`current=v1;v1=${key}`),reauthorize});await expect(gateway.create(actor,request,'same-key')).resolves.toMatchObject({id:metadata.id,state:'ready'});expect(reauthorize).toHaveBeenCalledWith(expect.anything(),actor,expect.objectContaining({selection:metadata.selection}));expect(resolveSelection).not.toHaveBeenCalled();});

  it('denies an expired replay after freshly reauthorizing its durable selection',async()=>{const row={id:metadata.id,org_id:metadata.orgId,subject_id:metadata.subjectId,actor_id:metadata.requestedBy,scope:metadata.request.scope,format:metadata.request.format,state:metadata.state,selection:metadata.selection,created_at:new Date(metadata.createdAt),expires_at:new Date('2026-09-11T01:00:00.000Z'),as_of:new Date(metadata.asOf!),source_version:metadata.sourceVersion!,plaintext_bytes:metadata.plaintextBytes!,failure_code:null,encryption_algorithm:null,key_version:null,nonce:null,auth_tag:null,ciphertext:null,request_hash:'a'.repeat(64)};const sql=Object.assign(async(strings:TemplateStringsArray)=>strings.join('').includes('from individual_report_exports')?[row]:strings.join('').includes('statement_timestamp() as now')?[{now:new Date('2026-09-11T12:00:00.000Z')}]:[],{unsafe:async()=>[],release:vi.fn()});const reauthorize=vi.fn(()=>Promise.resolve(true));const store=new PostgresIndividualExportStore({reserve:()=>Promise.resolve(sql)} as never,actor.orgId,'same-key','a'.repeat(64),reauthorize);await expect(store.findIdempotentAuthorized(actor)).resolves.toEqual({status:'denied'});expect(reauthorize).toHaveBeenCalledOnce();});
});
