import type { AnalyticsTile, AnalyticsTiles } from './types.ts';
import { createHash } from 'node:crypto';
export const DEFAULT_SUPPRESSION_THRESHOLD=11;
export interface AnalyticsSnapshot{asOf:string;users:number;content:number;partners:number;holds:number}
function hidden(key:string,unit:string,asOf:string):AnalyticsTile{return{key,value:0,unit_definition:`${unit} Stored rows as of ${asOf}.`,known_gap:'Suppressed to protect groups smaller than the configured threshold.'};}
function shown(key:string,value:number,unit:string,asOf:string):AnalyticsTile{return{key,value,unit_definition:`${unit} Stored rows as of ${asOf}.`,known_gap:null};}
/** Suppress both a subset and its total whenever either hidden partition is small. */
export function protectSubset(total:number,subset:number,k=DEFAULT_SUPPRESSION_THRESHOLD):{total:boolean;subset:boolean}{if(!Number.isSafeInteger(k)||k<2)throw new Error('suppression threshold must be at least 2');const remainder=total-subset;const sensitive=(subset>0&&subset<k)||(remainder>0&&remainder<k);return{total:sensitive,subset:sensitive||(subset>0&&subset<k)};}
export function analyticsFromSnapshot(snapshot:AnalyticsSnapshot,k=DEFAULT_SUPPRESSION_THRESHOLD):AnalyticsTiles{const userSuppression=protectSubset(snapshot.users,snapshot.holds,k);const units={users:'Current organisation user records; source: users.',content:'Current content pages, FAQs, and announcements; sources: content_pages, faqs, announcements.',partners:'Current partner organisation records; source: partners.',holds:'Accounts currently held for review; source: users.account_state.'};const sourceVersion=`wp-019-${createHash('sha256').update(JSON.stringify(snapshot)).digest('hex')}`;return{as_of:snapshot.asOf,source_version:sourceVersion,tiles:[userSuppression.total?hidden('users',units.users,snapshot.asOf):shown('users',snapshot.users,units.users,snapshot.asOf),snapshot.content>0&&snapshot.content<k?hidden('managed_content',units.content,snapshot.asOf):shown('managed_content',snapshot.content,units.content,snapshot.asOf),snapshot.partners>0&&snapshot.partners<k?hidden('partners',units.partners,snapshot.asOf):shown('partners',snapshot.partners,units.partners,snapshot.asOf),userSuppression.subset?hidden('review_holds',units.holds,snapshot.asOf):shown('review_holds',snapshot.holds,units.holds,snapshot.asOf)]};}
