import type { AssistanceRequest, AssistanceRequestPage, ModerationItem, ModerationItemPage, RideRequest, RideRequestPage, TranslationEntry, TranslationEntryPage } from '../../contracts/src/types.ts';
import type { Page, QueueDefinition, QueueItem, QueueKind, QueueTransport } from './types.ts';

type ParsedModeration=ModerationItem&{id:string;source:'ai_flag'|'user_report';target_type:'post'|'reply'|'message'};
type QueueRowByKind={assistance:AssistanceRequest;rides:RideRequest;moderation:ParsedModeration;translation:TranslationEntry};
const object=(value:unknown):Record<string,unknown>=>{if(typeof value!=='object'||value===null||Array.isArray(value))throw new QueueContractError('queue response must be an object');return value as Record<string,unknown>;};
const requiredString=(row:Record<string,unknown>,key:string):string=>{const value=row[key];if(typeof value!=='string'||value.length===0)throw new QueueContractError(`queue item ${key} must be a non-empty string`);return value;};
const optionalString=(row:Record<string,unknown>,key:string):string|null=>{const value=row[key];if(value===undefined||value===null)return null;if(typeof value!=='string'||value.length===0)throw new QueueContractError(`queue item ${key} must be a string or null`);return value;};
const uuid=(value:string,key:string):string=>{if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/iu.test(value))throw new QueueContractError(`queue item ${key} must be a UUID`);return value;};
const optionalUuid=(row:Record<string,unknown>,key:string):string|null=>{const value=optionalString(row,key);return value===null?null:uuid(value,key);};
const dateTime=(value:string,key:string):string=>{const match=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d+)?(?:Z|([+-])(\d{2}):(\d{2}))$/u.exec(value);if(!match)throw new QueueContractError(`queue item ${key} must be an RFC3339 date-time`);const part=(index:number):number=>Number(match[index]??Number.NaN);const [y,m,d,h,min,s,oh,om]=[1,2,3,4,5,6,8,9].map(part) as [number,number,number,number,number,number,number,number];if(m<1||m>12||d<1||d>new Date(Date.UTC(y,m,0)).getUTCDate()||h>23||min>59||s>59||(match[7]!==undefined&&(oh>23||om>59))||!Number.isFinite(Date.parse(value)))throw new QueueContractError(`queue item ${key} must be an RFC3339 date-time`);return value;};
const optionalDateTime=(row:Record<string,unknown>,key:string):string|null=>{const value=optionalString(row,key);return value===null?null:dateTime(value,key);};
const oneOf=<T extends string>(value:string,values:readonly T[],key:string):T=>{if(!values.includes(value as T))throw new QueueContractError(`queue item ${key} is outside the locked contract`);return value as T;};
function lockedPage<T>(value:unknown,parse:(item:unknown)=>T):Page<T>{const row=object(value);if(!Array.isArray(row.items))throw new QueueContractError('queue response items must be an array');const meta=object(row.meta);const cursor=meta.next_cursor;if(cursor!==undefined&&cursor!==null&&typeof cursor!=='string')throw new QueueContractError('queue meta.next_cursor is invalid');if(meta.total_known!==undefined&&typeof meta.total_known!=='boolean')throw new QueueContractError('queue meta.total_known is invalid');return{items:row.items.map(parse),meta:{next_cursor:typeof cursor==='string'?cursor:null,total_known:meta.total_known===true}};}
function assistance(value:unknown):AssistanceRequest{const row=object(value);const category=optionalString(row,'triage_category');return{id:uuid(requiredString(row,'id'),'id'),org_id:uuid(requiredString(row,'org_id'),'org_id'),state:oneOf(requiredString(row,'state'),['pending_unowned','owned','in_progress','resolved','closed_unable'] as const,'state'),...(category===null?{}:{triage_category:category}),owner_id:optionalUuid(row,'owner_id'),sla_due_at:optionalDateTime(row,'sla_due_at')};}
function ride(value:unknown):RideRequest{const row=object(value);const purpose=optionalString(row,'purpose');const pickupAt=optionalDateTime(row,'pickup_at');return{id:uuid(requiredString(row,'id'),'id'),org_id:uuid(requiredString(row,'org_id'),'org_id'),state:oneOf(requiredString(row,'state'),['draft','requested','waiting_for_dispatcher','confirmed_by','completed','cancelled','unable_to_fulfill'] as const,'state'),...(purpose===null?{}:{purpose}),...(pickupAt===null?{}:{pickup_at:pickupAt}),confirmed_by_actor:optionalString(row,'confirmed_by_actor'),confirmed_at:optionalDateTime(row,'confirmed_at')};}
function moderation(value:unknown):ParsedModeration{const row=object(value);const decision=optionalString(row,'decision');return{id:uuid(requiredString(row,'id'),'id'),source:oneOf(requiredString(row,'source'),['ai_flag','user_report'] as const,'source'),target_type:oneOf(requiredString(row,'target_type'),['post','reply','message'] as const,'target_type'),decision:decision===null?null:oneOf(decision,['keep','remove','warn'] as const,'decision'),decided_by:optionalUuid(row,'decided_by')};}
function translation(value:unknown):TranslationEntry{const row=object(value);return{id:uuid(requiredString(row,'id'),'id'),key:requiredString(row,'key'),locale:oneOf(requiredString(row,'locale'),['es'] as const,'locale'),source_version:requiredString(row,'source_version'),status:oneOf(requiredString(row,'status'),['draft','awaiting_review','approved','invalidated'] as const,'status')};}
function assistancePage(value:unknown):Page<AssistanceRequest>{const result=lockedPage(value,assistance);const checked={items:result.items,meta:result.meta} satisfies AssistanceRequestPage;return{items:checked.items,meta:result.meta};}
function ridePage(value:unknown):Page<RideRequest>{const result=lockedPage(value,ride);const checked={items:result.items,meta:result.meta} satisfies RideRequestPage;return{items:checked.items,meta:result.meta};}
function moderationPage(value:unknown):Page<ParsedModeration>{const result=lockedPage(value,moderation);const checked={items:result.items,meta:result.meta} satisfies ModerationItemPage;return{items:checked.items,meta:result.meta};}
function translationPage(value:unknown):Page<TranslationEntry>{const result=lockedPage(value,translation);const checked={items:result.items,meta:result.meta} satisfies TranslationEntryPage;return{items:checked.items,meta:result.meta};}
const definition=<K extends QueueKind>(value:QueueDefinition<QueueRowByKind[K]>)=>value;
export class QueueContractError extends Error{}
export const queueDefinitions={
  assistance:definition<'assistance'>({kind:'assistance',endpoint:'/api/v1/staff/assistance-requests',parse:assistancePage,item:row=>({id:row.id,queue:'assistance',label:row.triage_category??null,state:row.state,actor:row.owner_id??null,at:row.sla_due_at??null})}),
  rides:definition<'rides'>({kind:'rides',endpoint:'/api/v1/staff/rides',parse:ridePage,item:row=>({id:row.id,queue:'rides',label:row.purpose??null,state:row.state,actor:row.confirmed_by_actor??null,at:row.confirmed_at??null})}),
  moderation:definition<'moderation'>({kind:'moderation',endpoint:'/api/v1/staff/moderation-queue',parse:moderationPage,item:row=>({id:row.id,queue:'moderation',label:row.target_type,state:row.decision??'awaiting_review',actor:row.decided_by??null,at:null})}),
  translation:definition<'translation'>({kind:'translation',endpoint:'/api/v1/admin/translations?status=awaiting_review',parse:translationPage,item:row=>({id:row.id,queue:'translation',label:row.key,state:row.status,actor:null,at:null})}),
} satisfies {[K in QueueKind]:QueueDefinition<QueueRowByKind[K]>};
async function loadDefinition<T>(transport:QueueTransport,current:QueueDefinition<T>):Promise<Page<QueueItem>>{const source=current.parse(await transport.get(current.endpoint));return{items:source.items.map(current.item),meta:source.meta};}
export function loadQueue(transport:QueueTransport,kind:QueueKind):Promise<Page<QueueItem>>{switch(kind){case'assistance':return loadDefinition(transport,queueDefinitions.assistance);case'rides':return loadDefinition(transport,queueDefinitions.rides);case'moderation':return loadDefinition(transport,queueDefinitions.moderation);case'translation':return loadDefinition(transport,queueDefinitions.translation);}}
