// Generated from live Zod schemas by scripts/generate-types.ts. Do not edit by hand.
export type Problem = { "type": string; "title": string; "status": number; "detail"?: string; "instance"?: string; "human_route"?: string; [key: string]: unknown; };
export type PageMeta = { "next_cursor"?: string | null; "total_known"?: boolean; [key: string]: unknown; };
export type Org = { "id"?: string; "name"?: string; "locale_default"?: string; [key: string]: unknown; };
export type Me = { "user_id": string; "org_id": string; "roles": Array<"senior" | "caregiver" | "staff" | "admin" | "partner" | "support">; "mode": "standard" | "easy"; "locale": "en" | "es"; "acting_for"?: string | null; "active_scopes"?: Array<string>; "display_name"?: string; "preferences"?: Preferences; "consent_version"?: number; "demo_mode"?: boolean; "profile_id"?: string; };
export type Session = { "user_id"?: string; "expires_at"?: string; };
export type User = { "id"?: string; "org_id"?: string; "display_name"?: string; "roles"?: Array<"senior" | "caregiver" | "staff" | "admin" | "partner" | "support">; "account_state"?: "active" | "held_for_review" | "deactivated"; "version": number; };
export type UserPatch = { "roles"?: Array<"senior" | "caregiver" | "staff" | "admin" | "partner" | "support">; "account_state"?: string; "expected_version": number; };
export type UserPage = { "items"?: Array<User>; "meta"?: PageMeta; [key: string]: unknown; };
export type Profile = { "display_name"?: string; "preferred_name"?: string; "contact_email"?: string | null; "contact_phone"?: string | null; "accessibility_conditions"?: Array<string>; };
export type ProfilePatch = { [key: string]: unknown; };
export type Preferences = { "mode": "standard" | "easy"; "locale": "en" | "es"; "channels": { [key: string]: unknown; }; "quiet_hours": { "start"?: string; "end"?: string; "timezone"?: string; [key: string]: unknown; }; "no_outbound": boolean; "shared_device"?: boolean; };
export type MagicLinkRequest = { "email": string; [key: string]: unknown; };
export type SmsCodeRequest = { "phone": string; [key: string]: unknown; };
export type VerifyRequest = { "credential": string; "method"?: "magic_link" | "sms_code"; [key: string]: unknown; };
export type DemoCodeRequest = { "code": string; [key: string]: unknown; };
export type ServiceCategory = { "id"?: string; "label_en"?: string; "label_es"?: string; [key: string]: unknown; };
export type ServiceCategoryPage = { "items"?: Array<ServiceCategory>; [key: string]: unknown; };
export type Service = { "id"?: string; "org_id"?: string; "name"?: string; "category_id"?: string; "description"?: string; "eligibility_note"?: string; "phone"?: string; "languages"?: Array<string>; "accessibility"?: Array<string>; "source_updated_at"?: string; [key: string]: unknown; };
export type ServiceInput = { [key: string]: unknown; };
export type ServicePage = { "items"?: Array<Service>; "meta"?: PageMeta; [key: string]: unknown; };
export type CsvUpload = { "file"?: string; [key: string]: unknown; };
export type ImportResult = { "created"?: number; "updated"?: number; "rejected"?: Array<{ "row"?: number; "reason"?: string; [key: string]: unknown; }>; [key: string]: unknown; };
export type ConciergeConversation = { "id"?: string; "turns"?: Array<ConciergeAnswer>; "ai_enabled"?: boolean; [key: string]: unknown; };
export type ConciergeMessageInput = { "text": string; "locale"?: "en" | "es"; [key: string]: unknown; };
export type ConciergeAnswer = { "text": string; "citations": Array<string>; "disclaimer": string; "refused"?: boolean; "human_route"?: string; "prompt_version": string; [key: string]: unknown; };
export type Event = { "id"?: string; "org_id"?: string; "title"?: string; "starts_at"?: string; "time_zone"?: string; "location"?: string; "capacity"?: number | null; "rsvp_count"?: number; "accessibility"?: Array<string>; };
export type EventPage = { "items"?: Array<Event>; "meta"?: PageMeta; [key: string]: unknown; };
export type Rsvp = { "id"?: string; "event_id"?: string; "state"?: "attending" | "waitlisted" | "cancelled"; };
export type EventProposalInput = { "title": string; "starts_at": string; "time_zone"?: string; "note"?: string; };
export type EventProposal = { "id"?: string; "state"?: "proposed" | "published" | "declined"; "time_zone"?: string; };
export type RideRequest = { "id": string; "org_id": string; "purpose"?: string; "mode"?: "paratransit" | "taxi_voucher" | "rideshare" | "partner_van"; "pickup_at"?: string; "pickup_location"?: string; "return_needed"?: boolean; "accessibility_conditions"?: Array<string>; "accessibility_details"?: Array<{ "code": string; "label": string; }>; "state": "draft" | "requested" | "waiting_for_dispatcher" | "confirmed_by" | "completed" | "cancelled" | "unable_to_fulfill"; "confirmed_by_actor"?: string | null; "confirmed_at"?: string | null; "send_state"?: "not_sent" | "sent" | "send_failed"; [key: string]: unknown; };
export type RideRequestInput = { "accessibility_conditions"?: Array<string>; "accessibility_details"?: Array<{ "code": string; "label": string; }>; [key: string]: unknown; };
export type RideTransitionInput = { "to": string; "reason"?: string; [key: string]: unknown; };
export type RideRequestPage = { "items"?: Array<RideRequest>; "meta"?: PageMeta; [key: string]: unknown; };
export type AssistanceRequest = { "id": string; "org_id": string; "summary"?: string; "triage_category"?: string; "triage_source"?: "rules" | "ai" | "staff"; "state": "pending_unowned" | "owned" | "in_progress" | "resolved" | "closed_unable"; "owner_id"?: string | null; "sla_due_at"?: string | null; "after_hours"?: boolean; [key: string]: unknown; };
export type AssistanceRequestInput = { "summary": string; "locale"?: string; [key: string]: unknown; };
export type AssistanceTransitionInput = { "to": string; "owner_id"?: string; "reason"?: string; [key: string]: unknown; };
export type AssistanceRequestPage = { "items"?: Array<AssistanceRequest>; "meta"?: PageMeta; [key: string]: unknown; };
export type ForumTopic = { "id"?: string; "title"?: string; "post_count"?: number; [key: string]: unknown; };
export type ForumTopicPage = { "items"?: Array<ForumTopic>; "meta"?: PageMeta; [key: string]: unknown; };
export type ForumPost = { "id"?: string; "author_id"?: string; "body"?: string; "flag_state"?: "none" | "flagged_awaiting_human" | "cleared_by_human" | "removed_by_human"; [key: string]: unknown; };
export type ForumPostInput = { "body": string; [key: string]: unknown; };
export type ForumPostPage = { "items"?: Array<ForumPost>; "meta"?: PageMeta; [key: string]: unknown; };
export type ForumReply = { "id"?: string; "body"?: string; [key: string]: unknown; };
export type ForumReplyInput = { "body": string; [key: string]: unknown; };
export type ReportInput = { "reason": string; "note"?: string; [key: string]: unknown; };
export type Report = { "id"?: string; "state"?: "open" | "decided"; [key: string]: unknown; };
export type BlockInput = { "user_id": string; [key: string]: unknown; };
export type BlockPage = { "items"?: Array<{ [key: string]: unknown; }>; [key: string]: unknown; };
export type ModerationItem = { "id"?: string; "source"?: "ai_flag" | "user_report"; "target_type"?: "post" | "reply" | "message"; "decision"?: "keep" | "remove" | "warn" | null; "decided_by"?: string | null; [key: string]: unknown; };
export type ModerationDecisionInput = { "decision": string; "reason": string; [key: string]: unknown; };
export type ModerationItemPage = { "items"?: Array<ModerationItem>; "meta"?: PageMeta; [key: string]: unknown; };
export type Conversation = { "id"?: string; "participant_ids"?: Array<string>; [key: string]: unknown; };
export type ConversationInput = { "participant_id": string; [key: string]: unknown; };
export type ConversationPage = { "items"?: Array<Conversation>; "meta"?: PageMeta; [key: string]: unknown; };
export type Message = { "id"?: string; "body"?: string; "sent_at"?: string; [key: string]: unknown; };
export type MessageInput = { "body": string; [key: string]: unknown; };
export type MessagePage = { "items"?: Array<Message>; "meta"?: PageMeta; [key: string]: unknown; };
export type CaregiverInviteInput = { "email_or_phone": string; "relationship_note"?: string; };
export type CaregiverInvitation = { "id"?: string; "expires_at"?: string; };
export type ConsentScope = { "key": "view_schedule" | "book_rides" | "receive_alerts" | "view_assistance" | "manage_events" | "view_profile"; "granted": boolean; "granted_at"?: string | null; };
export type ConsentScopeSet = { "scopes": Array<ConsentScope>; "read_back_confirmed": boolean; };
export type CaregiverLink = { "id"?: string; "resident_id"?: string; "caregiver_id"?: string; "scopes"?: Array<ConsentScope>; "state"?: "pending" | "active" | "revoked"; };
export type CaregiverLinkPage = { "items"?: Array<CaregiverLink>; [key: string]: unknown; };
export type IntakeSubmissionInput = { "answers": { [key: string]: unknown; }; "disclaimer_acknowledged": boolean; "locale"?: "en" | "es"; "intent"?: "save_draft" | "submit"; };
export type IntakeSubmissionPatch = { "answers"?: { [key: string]: unknown; }; "disclaimer_acknowledged"?: boolean; "locale"?: "en" | "es"; "intent"?: "save_draft" | "submit"; };
export type IntakeSubmission = { "id"?: string; "kind"?: "legal" | "health"; "routed_to_partner_category"?: string; "answers"?: { [key: string]: unknown; }; "disclaimer_acknowledged"?: boolean; "locale"?: "en" | "es"; "state"?: "draft" | "submitted" | "routed" | "closed"; };
export type Notification = { "id"?: string; "purpose"?: string; "title"?: string; "body"?: string; "read_at"?: string | null; [key: string]: unknown; };
export type NotificationPage = { "items"?: Array<Notification>; "meta"?: PageMeta; [key: string]: unknown; };
export type PrintableSchedule = { "as_of": string; "source_version": string; "items": Array<{ [key: string]: unknown; }>; [key: string]: unknown; };
export type ContentPage = { "id"?: string; "slug"?: string; "version"?: number; "critical"?: boolean; [key: string]: unknown; };
export type ContentPageInput = { [key: string]: unknown; };
export type ContentPagePage = { "items"?: Array<ContentPage>; "meta"?: PageMeta; [key: string]: unknown; };
export type Faq = { "id"?: string; "question"?: string; "answer"?: string; "version"?: number; [key: string]: unknown; };
export type FaqInput = { [key: string]: unknown; };
export type FaqPage = { "items"?: Array<Faq>; "meta"?: PageMeta; [key: string]: unknown; };
export type Announcement = { "id"?: string; "title"?: string; "publish_at"?: string; [key: string]: unknown; };
export type AnnouncementInput = { [key: string]: unknown; };
export type AnnouncementPage = { "items"?: Array<Announcement>; "meta"?: PageMeta; [key: string]: unknown; };
export type Partner = { "id"?: string; "name"?: string; "categories"?: Array<string>; "contact"?: string; [key: string]: unknown; };
export type PartnerInput = { [key: string]: unknown; };
export type PartnerPage = { "items"?: Array<Partner>; "meta"?: PageMeta; [key: string]: unknown; };
export type AnalyticsTiles = { "as_of": string; "source_version": string; "tiles"?: Array<{ "key"?: string; "value"?: number; "unit_definition"?: string; "known_gap"?: string | null; [key: string]: unknown; }>; [key: string]: unknown; };
export type Report_ = { "name"?: string; "generated_at"?: string; "unit_definitions"?: { [key: string]: unknown; }; "known_gaps"?: Array<string>; "rows"?: Array<{ [key: string]: unknown; }>; "as_of"?: string; "source_version"?: string; "included_channels"?: Array<string>; "completeness"?: "complete" | "partial" | "unknown"; "known_omissions"?: Array<string>; "overlap_uncertainty"?: Array<string>; "filters"?: AggregateExportFilters; "scope"?: "tenant_aggregate"; "evidence"?: Array<string>; "suppression_threshold"?: number; [key: string]: unknown; };
export type ExportRequest = { "scope": Array<"profile" | "requests" | "consents" | "audit" | "proposals">; "format": "json" | "csv"; };
export type AggregateExportFilters = { "from"?: string; "to"?: string; "channels"?: Array<string>; };
export type AggregateExportRequest = { "report_name": "channel-activity"; "format": "json" | "csv"; "filters": AggregateExportFilters; };
export type ExportJob = { "id"?: string; "state"?: "queued" | "running" | "ready" | "failed"; "scope"?: Array<"profile" | "requests" | "consents" | "audit" | "proposals">; "completeness_note"?: string; "download_url"?: string | null; "expires_at"?: string | null; "report_name"?: "channel-activity"; "format"?: "json" | "csv"; "filters"?: AggregateExportFilters; "as_of"?: string; "source_version"?: string; "included_channels"?: Array<string>; "completeness"?: "complete" | "partial" | "unknown"; "known_omissions"?: Array<string>; "overlap_uncertainty"?: Array<string>; "row_count"?: number; "content_digest"?: string; };
export type TranslationEntry = { "id": string; "key": string; "locale": "es"; "source_version": string; "critical"?: boolean; "status": "draft" | "awaiting_review" | "approved" | "invalidated"; "machine_generated"?: boolean; [key: string]: unknown; };
export type TranslationApprovalInput = { "source_version": string; "reviewer_note": string; [key: string]: unknown; };
export type TranslationEntryPage = { "items"?: Array<TranslationEntry>; "meta"?: PageMeta; [key: string]: unknown; };
export type Flag = { "key": string; "enabled": boolean; "scope"?: "global" | "org"; "updated_by"?: string; [key: string]: unknown; };
export type FlagPatch = { "enabled": boolean; "reason"?: string; [key: string]: unknown; };
export type FlagPage = { "items"?: Array<Flag>; [key: string]: unknown; };
export type AiEvent = { "id"?: string; "org_id"?: string; "feature"?: string; "prompt_version"?: string; "provider"?: string; "model"?: string; "tokens_in"?: number; "tokens_out"?: number; "tokens_cached"?: number; "latency_ms"?: number; "cache_hit"?: boolean; "user_role"?: string; "outcome"?: "ok" | "refused" | "error" | "killed"; "cost_usd"?: number; "created_at"?: string; [key: string]: unknown; };
export type AiEventPage = { "items"?: Array<AiEvent>; "meta"?: PageMeta; [key: string]: unknown; };
export type AuditEvent = { "id"?: string; "actor"?: string; "on_behalf_of"?: string | null; "action"?: string; "target"?: string; "org_id"?: string; "at"?: string; "outcome"?: "allowed" | "denied" | "error"; "reason"?: string; "prompt_version"?: string | null; [key: string]: unknown; };
export type AuditEventPage = { "items"?: Array<AuditEvent>; "meta"?: PageMeta; [key: string]: unknown; };
export type HealthStatus = { "status": "ok" | "degraded" | "down"; "checks"?: { [key: string]: unknown; }; [key: string]: unknown; };
export interface ContractTypes {
  Problem: Problem;
  PageMeta: PageMeta;
  Org: Org;
  Me: Me;
  Session: Session;
  User: User;
  UserPatch: UserPatch;
  UserPage: UserPage;
  Profile: Profile;
  ProfilePatch: ProfilePatch;
  Preferences: Preferences;
  MagicLinkRequest: MagicLinkRequest;
  SmsCodeRequest: SmsCodeRequest;
  VerifyRequest: VerifyRequest;
  DemoCodeRequest: DemoCodeRequest;
  ServiceCategory: ServiceCategory;
  ServiceCategoryPage: ServiceCategoryPage;
  Service: Service;
  ServiceInput: ServiceInput;
  ServicePage: ServicePage;
  CsvUpload: CsvUpload;
  ImportResult: ImportResult;
  ConciergeConversation: ConciergeConversation;
  ConciergeMessageInput: ConciergeMessageInput;
  ConciergeAnswer: ConciergeAnswer;
  Event: Event;
  EventPage: EventPage;
  Rsvp: Rsvp;
  EventProposalInput: EventProposalInput;
  EventProposal: EventProposal;
  RideRequest: RideRequest;
  RideRequestInput: RideRequestInput;
  RideTransitionInput: RideTransitionInput;
  RideRequestPage: RideRequestPage;
  AssistanceRequest: AssistanceRequest;
  AssistanceRequestInput: AssistanceRequestInput;
  AssistanceTransitionInput: AssistanceTransitionInput;
  AssistanceRequestPage: AssistanceRequestPage;
  ForumTopic: ForumTopic;
  ForumTopicPage: ForumTopicPage;
  ForumPost: ForumPost;
  ForumPostInput: ForumPostInput;
  ForumPostPage: ForumPostPage;
  ForumReply: ForumReply;
  ForumReplyInput: ForumReplyInput;
  ReportInput: ReportInput;
  Report: Report;
  BlockInput: BlockInput;
  BlockPage: BlockPage;
  ModerationItem: ModerationItem;
  ModerationDecisionInput: ModerationDecisionInput;
  ModerationItemPage: ModerationItemPage;
  Conversation: Conversation;
  ConversationInput: ConversationInput;
  ConversationPage: ConversationPage;
  Message: Message;
  MessageInput: MessageInput;
  MessagePage: MessagePage;
  CaregiverInviteInput: CaregiverInviteInput;
  CaregiverInvitation: CaregiverInvitation;
  ConsentScope: ConsentScope;
  ConsentScopeSet: ConsentScopeSet;
  CaregiverLink: CaregiverLink;
  CaregiverLinkPage: CaregiverLinkPage;
  IntakeSubmissionInput: IntakeSubmissionInput;
  IntakeSubmissionPatch: IntakeSubmissionPatch;
  IntakeSubmission: IntakeSubmission;
  Notification: Notification;
  NotificationPage: NotificationPage;
  PrintableSchedule: PrintableSchedule;
  ContentPage: ContentPage;
  ContentPageInput: ContentPageInput;
  ContentPagePage: ContentPagePage;
  Faq: Faq;
  FaqInput: FaqInput;
  FaqPage: FaqPage;
  Announcement: Announcement;
  AnnouncementInput: AnnouncementInput;
  AnnouncementPage: AnnouncementPage;
  Partner: Partner;
  PartnerInput: PartnerInput;
  PartnerPage: PartnerPage;
  AnalyticsTiles: AnalyticsTiles;
  Report_: Report_;
  ExportRequest: ExportRequest;
  AggregateExportFilters: AggregateExportFilters;
  AggregateExportRequest: AggregateExportRequest;
  ExportJob: ExportJob;
  TranslationEntry: TranslationEntry;
  TranslationApprovalInput: TranslationApprovalInput;
  TranslationEntryPage: TranslationEntryPage;
  Flag: Flag;
  FlagPatch: FlagPatch;
  FlagPage: FlagPage;
  AiEvent: AiEvent;
  AiEventPage: AiEventPage;
  AuditEvent: AuditEvent;
  AuditEventPage: AuditEventPage;
  HealthStatus: HealthStatus;
}
