import {createHash} from 'node:crypto';
import {DEFAULT_REPORT_SUPPRESSION_THRESHOLD,type ActivityFact,type CanonicalReport,type ChannelCoverage,type Completeness,type ReportFilters,type ReportRow,type ReportSnapshot} from './types.ts';
export const reportingChannels=['screen','phone','sms','paper','front_desk','staff_assisted'] as const;
export const reportingMetrics=['requests','registrations','attendance','capacity','unmet_requests'] as const;
const dayMs=86_400_000;
const cleanList=(values:readonly string[])=>[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'en'));
const level=(values:readonly Completeness[]):Completeness=>values.includes('unknown')?'unknown':values.includes('partial')?'partial':'complete';
const safeEvidence=(value:string)=>/^[a-z][a-z0-9_.:-]{0,63}$/u.test(value);
function safeStatements(values:readonly string[],kind:string):string[]{const result=cleanList(values.map(value=>value.trim()));if(result.length>32||result.some(value=>value.length>240||/@|(?:^|[\\/])\.?creds?(?:[\\/]|$)|(?:secret|password|token|api[-_]?key)/iu.test(value)||/[0-9a-f]{8}-[0-9a-f-]{27}/iu.test(value)||/\b\d{7,}\b/u.test(value)))throw new Error(`${kind} contains unsafe or unbounded text`);return result;}
function utc(value:string|null,name:string):string|null{if(value===null)return null;if(!/^\d{4}-\d{2}-\d{2}T00:00:00(?:\.000)?Z$/u.test(value))throw new Error(`${name} must be a midnight RFC3339 UTC day boundary`);const date=new Date(value);if(Number.isNaN(date.valueOf()))throw new Error(`${name} is invalid`);return date.toISOString();}
export function normalizeFilters(filters:ReportFilters):ReportFilters{const from=utc(filters.from,'from');const to=utc(filters.to,'to');if(from&&to&&(from>=to||Date.parse(to)-Date.parse(from)>366*dayMs))throw new Error('range must be increasing and no longer than 366 days');const channels=cleanList(filters.channels.map(value=>value.trim()));if(channels.length>8||channels.some(value=>!reportingChannels.includes(value as never)))throw new Error('channels are invalid');return{from,to,channels};}
function periods(filters:ReportFilters,asOf:string):string[]{const cutoff=Date.parse(asOf);if(Number.isNaN(cutoff))throw new Error('as_of is invalid');const to=filters.to?Date.parse(filters.to):Math.floor(cutoff/dayMs)*dayMs;const from=filters.from?Date.parse(filters.from):to-30*dayMs;if(from>=to||to-from>366*dayMs)throw new Error('resolved range is invalid');const result:string[]=[];for(let value=from;value<to;value+=dayMs)result.push(new Date(value).toISOString());return result;}
function coverageUniverse(snapshot:ReportSnapshot,included:readonly string[]):ChannelCoverage[]{const byChannel=new Map(snapshot.coverage.map(item=>[item.channel,item]));return included.map(channel=>byChannel.get(channel)??{channel,completeness:'unknown',sourceVersion:'unobserved',evidence:'wp020.no_declared_source',coverageFrom:null,coverageTo:null,knownOmission:'no declared source; activity is unknown',overlapUncertainty:null});}
function isUnknown(item:ChannelCoverage|undefined,period:string):boolean{return !item||item.completeness==='unknown'||item.coverageFrom===null||item.coverageTo===null||period<item.coverageFrom||period>=item.coverageTo;}
function protectedRows(facts:readonly ActivityFact[],coverage:readonly ChannelCoverage[],included:readonly string[],range:readonly string[],threshold:number):ReportRow[]{const sums=new Map<string,number>();for(const fact of facts){if(!reportingMetrics.includes(fact.metric as never)||!range.includes(fact.period))continue;const key=`${fact.period}\0${fact.metric}\0${fact.channel}`;sums.set(key,(sums.get(key)??0)+fact.count);}const byCoverage=new Map(coverage.map(item=>[item.channel,item]));const rows:ReportRow[]=[];for(const period of range)for(const metric of reportingMetrics){const values=included.map(channel=>({channel,count:sums.get(`${period}\0${metric}\0${channel}`)??0,unknown:isUnknown(byCoverage.get(channel),period)}));const hidden=new Set(values.filter(item=>!item.unknown&&item.count>0&&item.count<threshold).map(item=>item.channel));if(hidden.size===1){const secondary=values.filter(item=>!item.unknown&&!hidden.has(item.channel)).sort((a,b)=>a.count-b.count||a.channel.localeCompare(b.channel,'en'))[0];if(secondary)hidden.add(secondary.channel);}const protectedTotal=hidden.size>0||values.some(item=>item.unknown);rows.push({period,channel:'all',metric,count:protectedTotal?null:values.reduce((sum,item)=>sum+item.count,0),suppressed:protectedTotal,suppression_reason:protectedTotal?'suppressed_to_prevent_small_cell_derivation_or_unknown_source':null});for(const item of values){const protectedValue=item.unknown||hidden.has(item.channel);rows.push({period,channel:item.channel,metric,count:protectedValue?null:item.count,suppressed:protectedValue,suppression_reason:item.unknown?'source_unknown_or_omitted':hidden.has(item.channel)?'suppressed_to_prevent_small_cell_or_derivable_remainder':null});}}return rows;}
export function buildCanonicalReport(snapshot:ReportSnapshot,filters:ReportFilters,threshold=DEFAULT_REPORT_SUPPRESSION_THRESHOLD):CanonicalReport{if(!Number.isSafeInteger(threshold)||threshold<2||threshold>1000)throw new Error('suppression threshold must be an integer from 2 to 1000');const normalized=normalizeFilters(filters);const included=normalized.channels.length?normalized.channels:[...reportingChannels];const coverage=coverageUniverse(snapshot,included);if(coverage.some(item=>!safeEvidence(item.evidence)))throw new Error('evidence must be a structured public code');const range=periods(normalized,snapshot.asOf);const facts=snapshot.facts.filter(item=>included.includes(item.channel));const evidence=cleanList(coverage.map(item=>item.evidence));const outside=coverage.flatMap(item=>range.some(period=>isUnknown(item,period))?[`${item.channel}: requested days outside declared coverage are unknown`]:[]);const omissions=safeStatements([...coverage.flatMap(item=>item.knownOmission?[`${item.channel}: ${item.knownOmission}`]:[]),...outside],'known omissions');const overlap=safeStatements(coverage.flatMap(item=>item.overlapUncertainty?[`${item.channel}: ${item.overlapUncertainty}`]:[]),'overlap uncertainty');const digestInput=JSON.stringify({asOf:snapshot.asOf,filters:normalized,sources:coverage.map(item=>({channel:item.channel,sourceVersion:item.sourceVersion,from:item.coverageFrom,to:item.coverageTo}))});const sourceVersion=`wp-020-${createHash('sha256').update(digestInput).digest('hex')}`;const publicFilters={...(normalized.from?{from:normalized.from}:{}),...(normalized.to?{to:normalized.to}:{}),...(normalized.channels.length?{channels:normalized.channels}:{})};const completeness=outside.length?'unknown':level(coverage.map(item=>item.completeness));return{name:'channel-activity',generated_at:snapshot.asOf,unit_definitions:{count:'Stored activity records in fixed UTC-day, channel, and metric cells. Null means privacy suppression or an unknown source; it never means zero.'},known_gaps:cleanList([...omissions,...overlap]),filters:publicFilters,scope:'tenant_aggregate',as_of:snapshot.asOf,source_version:sourceVersion,evidence,included_channels:included,completeness,known_omissions:omissions,overlap_uncertainty:overlap,suppression_threshold:threshold,rows:protectedRows(facts,coverage,included,range,threshold)};}
