import type {DatabaseClient,TenantTransaction} from '../../db/src/index.ts';
import type {EncryptedArtifact,ExportActor,ExportJobMetadata,IndividualExportStorePort,JsonObject,StoredExportJob} from '../../individual-exports/src/index.ts';

type Reauthorize=(sql:TenantTransaction,actor:ExportActor,metadata:ExportJobMetadata)=>Promise<boolean>;
type Row={id:string;org_id:string;subject_id:string;actor_id:string;scope:ExportJobMetadata['request']['scope'];format:ExportJobMetadata['request']['format'];state:ExportJobMetadata['state'];selection:ExportJobMetadata['selection'];created_at:Date;expires_at:Date;as_of:Date|null;source_version:string|null;plaintext_bytes:number|null;failure_code:string|null;encryption_algorithm:'aes-256-gcm'|null;key_version:string|null;nonce:Uint8Array|null;auth_tag:Uint8Array|null;ciphertext:Uint8Array|null};
const canonicalSelection=(selection:ExportJobMetadata['selection'])=>JSON.stringify({orgId:selection.orgId,subjectId:selection.subjectId,profile:selection.profile??false,consents:selection.consents??false,requestIds:[...(selection.requestIds??[])].sort(),auditResourceIds:[...(selection.auditResourceIds??[])].sort(),proposalIds:[...(selection.proposalIds??[])].sort()});
const jsonSelection=(selection:ExportJobMetadata['selection']):JsonObject=>({orgId:selection.orgId,subjectId:selection.subjectId,...(selection.profile?{profile:true}:{}),...(selection.consents?{consents:true}:{}),...(selection.requestIds?{requestIds:[...selection.requestIds]}:{}),...(selection.auditResourceIds?{auditResourceIds:[...selection.auditResourceIds]}:{}),...(selection.proposalIds?{proposalIds:[...selection.proposalIds]}:{})});
export class ExistingIndividualExport extends Error{constructor(readonly stored:StoredExportJob,readonly requestHash:string){super('individual export already exists');}}
export type IndividualReplay={status:'absent'}|{status:'denied'}|{status:'authorized';stored:StoredExportJob;requestHash:string};
export class PostgresIndividualExportStore implements IndividualExportStorePort{
  constructor(private readonly client:DatabaseClient,private readonly orgId:string,private readonly mutationKey:string,private readonly requestHash:string,private readonly reauthorize:Reauthorize){}
  private async tx<T>(isolation:'read committed'|'serializable',work:(sql:TenantTransaction)=>Promise<T>):Promise<T>{const sql=await this.client.reserve();try{await sql.unsafe(`begin isolation level ${isolation}`);await sql`select set_config('app.current_org_id',${this.orgId},true)`;const value=await work(sql);await sql`commit`;return value;}catch(error){await sql`rollback`;throw error;}finally{sql.release();}}
  private async databaseNow(sql:TenantTransaction):Promise<Date>{const row=(await sql<Array<{now:Date}>>`select statement_timestamp() as now`)[0];if(!row)throw new Error('database time unavailable');return row.now;}
  private async row(sql:TenantTransaction,id:string,lock=false):Promise<Row|null>{const suffix=lock?' for update':'';const rows=await sql.unsafe<Row[]>(`select id,org_id,subject_id,actor_id,scope,format,state,selection,created_at,expires_at,as_of,source_version,plaintext_bytes,failure_code,encryption_algorithm,key_version,nonce,auth_tag,ciphertext from individual_report_exports where org_id=$1 and id=$2${suffix}`,[this.orgId,id]);return rows[0]??null;}
  private stored(row:Row):StoredExportJob{const metadata:ExportJobMetadata={id:row.id,orgId:row.org_id,subjectId:row.subject_id,requestedBy:row.actor_id,request:{scope:row.scope,format:row.format},selection:row.selection,state:row.state,createdAt:row.created_at.toISOString(),expiresAt:row.expires_at.toISOString(),...(row.as_of?{asOf:row.as_of.toISOString()}:{}),...(row.source_version?{sourceVersion:row.source_version}:{}),...(row.plaintext_bytes===null?{}:{plaintextBytes:row.plaintext_bytes}),...(row.failure_code?{failureCode:row.failure_code}:{})};const artifact=row.encryption_algorithm&&row.key_version&&row.nonce&&row.auth_tag&&row.ciphertext?{algorithm:row.encryption_algorithm,keyVersion:row.key_version,nonce:row.nonce,tag:row.auth_tag,ciphertext:row.ciphertext}:undefined;return{metadata,...(artifact?{artifact}:{})};}
  async createGenerating(metadata:ExportJobMetadata):Promise<void>{await this.tx('read committed',async sql=>{const inserted=(await sql<Array<{id:string}>>`insert into individual_report_exports(id,org_id,subject_id,actor_id,mutation_key,request_hash,scope,format,state,selection,created_at,expires_at) values(${metadata.id},${metadata.orgId},${metadata.subjectId},${metadata.requestedBy},${this.mutationKey},${this.requestHash},${metadata.request.scope as string[]},${metadata.request.format},'generating',${sql.json(jsonSelection(metadata.selection))},${metadata.createdAt},${metadata.expiresAt}) on conflict(org_id,actor_id,mutation_key) do nothing returning id`)[0];if(inserted)return;const existing=(await sql<Array<Row&{request_hash:string}>>`select id,org_id,subject_id,actor_id,scope,format,state,selection,created_at,expires_at,as_of,source_version,plaintext_bytes,failure_code,encryption_algorithm,key_version,nonce,auth_tag,ciphertext,request_hash from individual_report_exports where org_id=${metadata.orgId} and actor_id=${metadata.requestedBy} and mutation_key=${this.mutationKey}`)[0];if(!existing)throw new Error('idempotent individual export unavailable');throw new ExistingIndividualExport(this.stored(existing),existing.request_hash);});}
  async findIdempotentAuthorized(actor:ExportActor):Promise<IndividualReplay>{return this.tx('serializable',async sql=>{const existing=(await sql<Array<Row&{request_hash:string}>>`select id,org_id,subject_id,actor_id,scope,format,state,selection,created_at,expires_at,as_of,source_version,plaintext_bytes,failure_code,encryption_algorithm,key_version,nonce,auth_tag,ciphertext,request_hash from individual_report_exports where org_id=${this.orgId} and actor_id=${actor.userId} and mutation_key=${this.mutationKey} for update`)[0];if(!existing)return{status:'absent'};const stored=this.stored(existing),authorized=await this.reauthorize(sql,actor,stored.metadata),now=await this.databaseNow(sql);if(!authorized||existing.expires_at.getTime()<=now.getTime())return{status:'denied'};return{status:'authorized',stored,requestHash:existing.request_hash};});}
  async commitReadyIfAuthorized(metadata:ExportJobMetadata,artifact:EncryptedArtifact,actor:ExportActor):Promise<boolean>{return this.tx('serializable',async sql=>{const current=await this.row(sql,metadata.id,true);const asOf=metadata.asOf,sourceVersion=metadata.sourceVersion,plaintextBytes=metadata.plaintextBytes;if(!current||asOf===undefined||sourceVersion===undefined||plaintextBytes===undefined)return false;const now=await this.databaseNow(sql);const unchanged=current.org_id===metadata.orgId&&current.actor_id===metadata.requestedBy&&current.subject_id===metadata.subjectId&&current.format===metadata.request.format&&JSON.stringify(current.scope)===JSON.stringify(metadata.request.scope)&&canonicalSelection(current.selection)===canonicalSelection(metadata.selection)&&current.created_at.getTime()===Date.parse(metadata.createdAt)&&current.expires_at.getTime()===Date.parse(metadata.expiresAt);if(current.state!=='generating'||!unchanged||current.expires_at.getTime()<=now.getTime()||!await this.reauthorize(sql,actor,metadata))return false;await sql`update individual_report_exports set state='ready',as_of=${asOf},source_version=${sourceVersion},plaintext_bytes=${plaintextBytes},encryption_algorithm=${artifact.algorithm},key_version=${artifact.keyVersion},nonce=${artifact.nonce},auth_tag=${artifact.tag},ciphertext=${artifact.ciphertext} where org_id=${this.orgId} and id=${metadata.id} and state='generating'`;await sql`insert into audit_events(actor,action,target,org_id,outcome,reason,fields) values(${`user:${actor.userId}`},'export.created',${`individual_export:${metadata.id}`},${this.orgId},'allowed',${`scope=individual;format=${metadata.request.format};section_count=${metadata.request.scope.length}`},${['scope','format','section_count']})`;return true;});}
  async markFailed(jobId:string,failureCode:string):Promise<void>{await this.tx('read committed',async sql=>{await sql`update individual_report_exports set state='failed',failure_code=${failureCode},as_of=null,source_version=null,plaintext_bytes=null,encryption_algorithm=null,key_version=null,nonce=null,auth_tag=null,ciphertext=null where org_id=${this.orgId} and id=${jobId} and state='generating'`;});}
  async findAuthorized(jobId:string,actor:ExportActor):Promise<StoredExportJob|null>{return this.tx('serializable',async sql=>{const current=await this.row(sql,jobId);if(!current)return null;const stored=this.stored(current),authorized=await this.reauthorize(sql,actor,stored.metadata),now=await this.databaseNow(sql);if(!authorized||current.expires_at.getTime()<=now.getTime())return null;return stored;});}
  async authorizeReleaseAndRecord(jobId:string,actor:ExportActor,releasedAt:string):Promise<boolean>{return this.tx('serializable',async sql=>{const current=await this.row(sql,jobId,true);if(!current||current.state!=='ready')return false;const now=await this.databaseNow(sql);if(current.expires_at.getTime()<=now.getTime())return false;const stored=this.stored(current);if(!await this.reauthorize(sql,actor,stored.metadata))return false;await sql`update individual_report_exports set released_at=${releasedAt} where org_id=${this.orgId} and id=${jobId}`;await sql`insert into audit_events(actor,action,target,org_id,outcome,reason,fields) values(${`user:${actor.userId}`},'export.downloaded',${`individual_export:${jobId}`},${this.orgId},'allowed',${`scope=individual;format=${current.format};section_count=${current.scope.length}`},${['scope','format','section_count']})`;return true;});}
}
