import {createHash} from 'node:crypto';
import type {DatabaseClient,TenantTransaction} from '../../db/src/index.ts';
import {IndividualExportFault,IndividualExportService,exportSections,type ExportActor,type ExportEncryptionKeyProvider,type ExportJobMetadata,type IndividualExportAuthorityPort,type IndividualExportRequest,type IndividualExportSnapshotPort} from '../../individual-exports/src/index.ts';
import {ExistingIndividualExport,PostgresIndividualExportStore} from './individual-store.ts';

export interface IndividualApiJob{id:string;state:'running'|'ready'|'failed';scope:readonly string[];completeness_note:string;download_url:string|null;expires_at:string}
export interface IndividualApiArtifact{bytes:Uint8Array;contentType:string;filename:string}
export interface IndividualGateway{create(actor:ExportActor,request:IndividualExportRequest,key:string):Promise<IndividualApiJob>;get(actor:ExportActor,id:string):Promise<IndividualApiJob|null>;download(actor:ExportActor,id:string,accept:string|null):Promise<IndividualApiArtifact|null>}
export interface IndividualGatewayPorts{client:DatabaseClient;authority:IndividualExportAuthorityPort;snapshots:IndividualExportSnapshotPort;keys:ExportEncryptionKeyProvider;reauthorize(sql:TenantTransaction,actor:ExportActor,metadata:ExportJobMetadata):Promise<boolean>}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;
const apiJob=(metadata:ExportJobMetadata):IndividualApiJob=>({id:metadata.id,state:metadata.state==='generating'?'running':metadata.state,scope:metadata.request.scope,completeness_note:metadata.state==='ready'?'complete':metadata.state==='failed'?'failed without artifact':'generation in progress',download_url:metadata.state==='ready'?`/api/v1/admin/exports/${metadata.id}/download`:null,expires_at:metadata.expiresAt});
const normalized=(request:IndividualExportRequest):IndividualExportRequest=>({scope:exportSections.filter(section=>request.scope.includes(section)),format:request.format});
// eslint-disable-next-line @typescript-eslint/unbound-method -- injected port callback has no gateway receiver contract
export function createIndividualGateway(ports:IndividualGatewayPorts):IndividualGateway{const store=(actor:ExportActor,key='',hash='')=>new PostgresIndividualExportStore(ports.client,actor.orgId,key,hash,ports.reauthorize);return{async create(actor,raw,key){if(!key||key.length>160||!/^[A-Za-z0-9._~-]+$/u.test(key))throw new IndividualExportFault(422,'invalid_idempotency_key','Idempotency-Key is invalid');const request=normalized(raw);const hash=createHash('sha256').update(JSON.stringify(request)).digest('hex');const persistence=store(actor,key,hash),replay=await persistence.findIdempotentAuthorized(actor);if(replay.status==='denied')throw new IndividualExportFault(404,'export_unavailable','export is unavailable');if(replay.status==='authorized'){if(replay.requestHash!==hash)throw new IndividualExportFault(409,'idempotency_conflict','Idempotency-Key was reused for different content');return apiJob(replay.stored.metadata);}try{const ready=await new IndividualExportService({...ports,store:persistence}).create(actor,request);return{id:ready.id,state:'ready',scope:ready.scope,completeness_note:ready.completenessNote,download_url:`/api/v1/admin/exports/${ready.id}/download`,expires_at:ready.expiresAt};}catch(error){if(error instanceof ExistingIndividualExport){const old=await persistence.findAuthorized(error.stored.metadata.id,actor);if(!old)throw new IndividualExportFault(404,'export_unavailable','export is unavailable');if(error.requestHash!==hash)throw new IndividualExportFault(409,'idempotency_conflict','Idempotency-Key was reused for different content');return apiJob(old.metadata);}throw error;}},async get(actor,id){if(!uuid.test(id))throw new IndividualExportFault(422,'invalid_export_id','export id is invalid');const found=await store(actor).findAuthorized(id,actor);return found?apiJob(found.metadata):null;},async download(actor,id,accept){if(!uuid.test(id))throw new IndividualExportFault(422,'invalid_export_id','export id is invalid');const persistence=store(actor);const found=await persistence.findAuthorized(id,actor);if(!found)return null;const expected=found.metadata.request.format==='json'?'application/json':'application/zip';if(accept!==null&&accept!=='*/*'&&!accept.split(',').some(value=>expected.startsWith(value.trim().split(';')[0]??'')))throw new IndividualExportFault(409,'format_mismatch','stored export format does not match Accept');const released=await new IndividualExportService({...ports,store:persistence}).release(actor,id);return{bytes:released.bytes,contentType:released.contentType,filename:released.filename};}};}
