import {createHash} from 'node:crypto';
import {reportingChannels,reportingMetrics} from './canonical.ts';
import type {AggregateSourceFact,AggregateSourceCoverage,NormalizedAggregateSourceImport} from './types.ts';
const dayMs=86_400_000;
const record=(value:unknown):value is Record<string,unknown>=>typeof value==='object'&&value!==null&&!Array.isArray(value);
const safeStatement=(value:unknown):value is string=>typeof value==='string'&&value.length>0&&value.length<=240&&!/@|(?:^|[\\/])\.?creds?(?:[\\/]|$)|(?:secret|password|token|api[-_]?key)/iu.test(value)&&!/[0-9a-f]{8}-[0-9a-f-]{27}/iu.test(value)&&!/\b\d{7,}\b/u.test(value);
const sourceVersion=(value:unknown):value is string=>typeof value==='string'&&/^[a-z0-9][a-z0-9._:-]{0,127}$/u.test(value);
const evidenceCode=(value:unknown):value is string=>typeof value==='string'&&/^[a-z][a-z0-9_.:-]{0,63}$/u.test(value);
const utcDay=(value:unknown):string|null=>{if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}T00:00:00(?:\.000)?Z$/u.test(value))return null;const date=new Date(value);return Number.isNaN(date.valueOf())?null:date.toISOString();};
function coverageItem(value:unknown):Required<AggregateSourceCoverage>{if(!record(value)||typeof value.channel!=='string'||!reportingChannels.includes(value.channel as never)||!['complete','partial','unknown'].includes(String(value.completeness))||!evidenceCode(value.evidence)||(value.knownOmission!==undefined&&value.knownOmission!==null&&!safeStatement(value.knownOmission))||(value.overlapUncertainty!==undefined&&value.overlapUncertainty!==null&&!safeStatement(value.overlapUncertainty)))throw new Error('invalid source coverage');const from=utcDay(value.from);const to=utcDay(value.to);if(!from||!to||from>=to||Date.parse(to)-Date.parse(from)>366*dayMs)throw new Error('invalid source coverage interval');return{channel:value.channel,from,to,completeness:value.completeness as 'complete'|'partial'|'unknown',evidence:value.evidence,knownOmission:value.knownOmission??null,overlapUncertainty:value.overlapUncertainty??null};}
function factItem(value:unknown,coverage:ReadonlyMap<string,Required<AggregateSourceCoverage>>):AggregateSourceFact{if(!record(value)||typeof value.channel!=='string'||typeof value.metric!=='string'||!evidenceCode(value.evidence)||!reportingChannels.includes(value.channel as never)||!reportingMetrics.includes(value.metric as never)||!Number.isSafeInteger(value.count)||Number(value.count)<0||Number(value.count)>1_000_000_000)throw new Error('invalid source fact');const period=utcDay(value.period);const declared=coverage.get(value.channel);if(!period||!declared||period<declared.from||period>=declared.to)throw new Error('source fact is outside declared coverage');return{period,channel:value.channel,metric:value.metric,count:Number(value.count),evidence:value.evidence};}
export function normalizeAggregateSourceImport(value:unknown):NormalizedAggregateSourceImport{if(!record(value)||!sourceVersion(value.sourceVersion)||!Array.isArray(value.facts)||value.facts.length>2000||!Array.isArray(value.coverage)||value.coverage.length>reportingChannels.length)throw new Error('invalid aggregate source import');const coverage=value.coverage.map(coverageItem);if(new Set(coverage.map(item=>item.channel)).size!==coverage.length)throw new Error('duplicate source coverage');const byChannel=new Map(coverage.map(item=>[item.channel,item]));const facts=value.facts.map(item=>factItem(item,byChannel));const cells=facts.map(item=>`${item.period}\0${item.channel}\0${item.metric}`);if(new Set(cells).size!==cells.length)throw new Error('duplicate source fact');return{sourceVersion:value.sourceVersion,facts:[...facts].sort((a,b)=>a.period.localeCompare(b.period)||a.channel.localeCompare(b.channel)||a.metric.localeCompare(b.metric)),coverage:[...coverage].sort((a,b)=>a.channel.localeCompare(b.channel))};}
export function aggregateSourceRequestHash(input:NormalizedAggregateSourceImport):string{return createHash('sha256').update(JSON.stringify(input)).digest('hex');}
