import {reportingChannels,reportingMetrics} from './canonical.ts';
import type {CanonicalReport,ExportJob,PublicReportFilters,ReportRow} from './types.ts';
const rfc3339=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/u;const utcDay=/^\d{4}-\d{2}-\d{2}T00:00:00\.000Z$/u;const digest=/^[0-9a-f]{64}$/u;const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;const dayMs=86_400_000;
const record=(value:unknown):value is Record<string,unknown>=>typeof value==='object'&&value!==null&&!Array.isArray(value);
const exactKeys=(value:Record<string,unknown>,expected:readonly string[])=>Object.keys(value).length===expected.length&&expected.every(key=>key in value);
const strings=(value:unknown,max:number)=>Array.isArray(value)&&value.length<=max&&value.every(item=>typeof item==='string'&&item.length>0&&item.length<=240)&&new Set(value).size===value.length;
const sorted=(values:readonly string[])=>[...values].sort((a,b)=>a.localeCompare(b,'en'));
const channelList=(value:unknown):value is string[]=>strings(value,8)&&(value as string[]).every(item=>reportingChannels.includes(item as never));
const safeStatements=(value:unknown)=>strings(value,32)&&!(value as string[]).some(item=>/@|(?:^|[\\/])\.?creds?(?:[\\/]|$)|(?:secret|password|token|api[-_]?key)|[0-9a-f]{8}-[0-9a-f-]{27}|\b\d{7,}\b/iu.test(item));
const evidenceCodes=(value:unknown)=>strings(value,32)&&(value as string[]).every(item=>/^[a-z][a-z0-9_.:-]{0,63}$/u.test(item));
function filters(value:unknown):value is PublicReportFilters{if(!record(value)||Object.keys(value).some(key=>!['from','to','channels'].includes(key)))return false;const from=value.from,to=value.to,channels=value.channels;if((from!==undefined&&(typeof from!=='string'||!utcDay.test(from)))||(to!==undefined&&(typeof to!=='string'||!utcDay.test(to)))||(from!==undefined&&to!==undefined&&(from>=to||Date.parse(to)-Date.parse(from)>366*dayMs))||(channels!==undefined&&(!channelList(channels)||JSON.stringify(channels)!==JSON.stringify(sorted(channels)))))return false;return true;}
function expectedPeriods(filtersValue:PublicReportFilters,asOf:string):string[]{const to=filtersValue.to?Date.parse(filtersValue.to):Math.floor(Date.parse(asOf)/dayMs)*dayMs;const from=filtersValue.from?Date.parse(filtersValue.from):to-30*dayMs;if(!Number.isFinite(from)||from>=to||to-from>366*dayMs)return[];const result:string[]=[];for(let value=from;value<to;value+=dayMs)result.push(new Date(value).toISOString());return result;}
function rowValid(row:unknown):row is ReportRow{return record(row)&&exactKeys(row,['period','channel','metric','count','suppressed','suppression_reason'])&&typeof row.period==='string'&&utcDay.test(row.period)&&(row.channel==='all'||reportingChannels.includes(row.channel as never))&&reportingMetrics.includes(row.metric as never)&&(row.count===null||Number.isSafeInteger(row.count)&&Number(row.count)>=0)&&typeof row.suppressed==='boolean'&&(row.suppression_reason===null||typeof row.suppression_reason==='string'&&['source_unknown_or_omitted','suppressed_to_prevent_small_cell_or_derivable_remainder','suppressed_to_prevent_small_cell_derivation_or_unknown_source'].includes(row.suppression_reason))&&(row.suppressed?row.count===null&&row.suppression_reason!==null:row.count!==null&&row.suppression_reason===null);}
function rowsValid(rows:unknown,included:readonly string[],filtersValue:PublicReportFilters,asOf:string):boolean{if(!Array.isArray(rows))return false;const periods=expectedPeriods(filtersValue,asOf);if(rows.length!==periods.length*reportingMetrics.length*(included.length+1))return false;let offset=0;for(const period of periods)for(const metric of reportingMetrics){const group=rows.slice(offset,offset+included.length+1);offset+=included.length+1;const expected=['all',...included];if(group.some((row,index)=>!rowValid(row)||row.period!==period||row.metric!==metric||row.channel!==expected[index]))return false;const total=group[0] as ReportRow;const children=group.slice(1) as ReportRow[];if(children.some(row=>row.suppressed)){if(!total.suppressed)return false;}else if(total.suppressed||total.count!==children.reduce((sum,row)=>sum+(row.count??0),0))return false;}return true;}
export function assertChannelActivityReport(value:unknown):asserts value is CanonicalReport{const keys=['name','generated_at','unit_definitions','known_gaps','rows','filters','scope','as_of','source_version','evidence','included_channels','completeness','known_omissions','overlap_uncertainty','suppression_threshold'];if(!record(value)||!exactKeys(value,keys)||value.name!=='channel-activity'||value.scope!=='tenant_aggregate'||!filters(value.filters)||typeof value.generated_at!=='string'||!rfc3339.test(value.generated_at)||value.generated_at!==value.as_of||typeof value.as_of!=='string'||!rfc3339.test(value.as_of)||!record(value.unit_definitions)||!exactKeys(value.unit_definitions,['count'])||typeof value.unit_definitions.count!=='string'||!safeStatements(value.known_gaps)||typeof value.source_version!=='string'||!/^wp-020-[0-9a-f]{64}$/u.test(value.source_version)||!channelList(value.included_channels)||!['complete','partial','unknown'].includes(String(value.completeness))||!safeStatements(value.known_omissions)||!safeStatements(value.overlap_uncertainty)||!evidenceCodes(value.evidence)||!Number.isSafeInteger(value.suppression_threshold)||Number(value.suppression_threshold)<2||!rowsValid(value.rows,value.included_channels,value.filters,value.as_of))throw new Error('invalid channel-activity report envelope');const gaps=sorted([...(value.known_omissions as string[]),...(value.overlap_uncertainty as string[])]);if(JSON.stringify(value.known_gaps)!==JSON.stringify([...new Set(gaps)]))throw new Error('invalid channel-activity known gaps');const expected=value.filters.channels??[...reportingChannels];if(JSON.stringify(value.included_channels)!==JSON.stringify(expected))throw new Error('invalid channel-activity channel universe');}
export function assertAggregateExportJob(value:unknown):asserts value is ExportJob{const keys=['id','state','report_name','format','filters','as_of','source_version','included_channels','completeness','known_omissions','overlap_uncertainty','row_count','content_digest','completeness_note','download_url','expires_at'];if(!record(value)||!exactKeys(value,keys)||typeof value.id!=='string'||!uuid.test(value.id)||value.state!=='ready'||value.report_name!=='channel-activity'||!['json','csv'].includes(String(value.format))||!filters(value.filters)||typeof value.as_of!=='string'||!rfc3339.test(value.as_of)||typeof value.source_version!=='string'||!/^wp-020-[0-9a-f]{64}$/u.test(value.source_version)||!channelList(value.included_channels)||JSON.stringify(value.included_channels)!==JSON.stringify(value.filters.channels??[...reportingChannels])||!['complete','partial','unknown'].includes(String(value.completeness))||!safeStatements(value.known_omissions)||!safeStatements(value.overlap_uncertainty)||!Number.isSafeInteger(value.row_count)||Number(value.row_count)<0||typeof value.content_digest!=='string'||!digest.test(value.content_digest)||typeof value.completeness_note!=='string'||value.completeness_note.length<1||value.completeness_note.length>500||typeof value.download_url!=='string'||typeof value.expires_at!=='string'||!rfc3339.test(value.expires_at))throw new Error('invalid ready aggregate export job');}
