import { createHash } from 'node:crypto';
import { AmbiguousProviderTimeoutError, EgressBlockedError, PossiblyBilledProviderError, ProviderUsageMissingError } from './providers.ts';
import type { AiEventWriter, CacheBoundary, ExactCache, FlagReader, PriceBook, Prompt, PromptRegistry, RateLimiter, ReservationStore, Route, Router } from './ports.ts';
import { AiRateLimited } from './types.ts';
import type { AiChatRequest, AiChatResult, AiClassifyRequest, AiClassifyResult, AiContext, AiEmbedRequest, AiEmbedResult, AiFeature, AiGateway, AiMessage, AiOutcome, AiProviderAdapter, AiProviderResponse, AiProviderUsage, AiSummarizeRequest, AiSummarizeResult, AiTranslateRequest, AiTranslateResult, CacheKey, CostReservation } from './types.ts';

const routes: Record<AiFeature, string> = { concierge: '/assistance', moderation: '/report', translation_assist: '/language-help', triage: '/assistance', intake_routing: '/assistance', event_rerank: '/events', conversation_starters: '/groups', summaries: '/support' };
const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;
const code = { killed: 'AI_KILLED', killedResult: 'AI_KILLED_BEFORE_RESULT', rate: 'AI_RATE_LIMITED', unsupported: 'PROVIDER_CAPABILITY_UNAVAILABLE', egress: 'EGRESS_POLICY_BLOCKED', timeout: 'PROVIDER_TIMEOUT_AMBIGUOUS', transport: 'PROVIDER_TRANSPORT_UNCERTAIN', usage: 'PROVIDER_USAGE_MISSING', structured: 'PROVIDER_STRUCTURED_OUTPUT_INVALID', reserve: 'COST_RESERVATION_REJECTED', exceeded: 'COST_RESERVATION_EXCEEDED', provider: 'PROVIDER_CALL_FAILED', refusal: 'MODEL_REFUSAL' } as const;

export interface GatewayOptions { flags: FlagReader; events: AiEventWriter; prompts: PromptRegistry; router: Router; providers: ReadonlyMap<string, AiProviderAdapter>; rateLimiter: RateLimiter; reservations: ReservationStore; cache: ExactCache; cacheBoundary: CacheBoundary; prices: PriceBook; maxGatewayRetries?: 0 | 1; totalDeadlineMs?: number; now?: () => number }
interface Invocation { feature: AiFeature; context: AiContext; messages: readonly AiMessage[]; tools?: AiChatRequest['tools']; schema?: AiChatRequest['schema']; maxTokens?: number; temperature?: number; cacheEligible: boolean }
interface Core { response?: AiProviderResponse; outcome: AiOutcome; reason?: string; humanRoute?: string; eventId: string; cacheHit: boolean; prompt?: Prompt; route: Route }
interface Envelope { response?: AiProviderResponse; error?: unknown; uncertain: boolean; attempts: number }
interface Estimator extends AiProviderAdapter { estimateSerializedBytes?(input: { system: string; messages: readonly AiMessage[]; tools?: AiChatRequest['tools']; schema?: AiChatRequest['schema']; maxTokens: number; temperature?: number }): number }

export class DefaultAiGateway implements AiGateway {
  private readonly retries: 0 | 1; private readonly deadlineMs: number; private readonly now: () => number;
  constructor(private readonly options: GatewayOptions) { this.retries = options.maxGatewayRetries ?? 1; this.deadlineMs = options.totalDeadlineMs ?? 15_000; this.now = options.now ?? Date.now; }
  async chat(req: AiChatRequest): Promise<AiChatResult> { const core = await this.invoke({ feature: req.feature, context: req.context, messages: req.messages, ...(req.tools ? { tools: req.tools } : {}), ...(req.schema ? { schema: req.schema } : {}), ...(req.maxTokens !== undefined ? { maxTokens: req.maxTokens } : {}), ...(req.temperature !== undefined ? { temperature: req.temperature } : {}), cacheEligible: true }); return { ...this.base(core), text: core.response?.text ?? '', toolCalls: core.response?.toolCalls ?? [], ...(core.response?.structured !== undefined ? { structured: core.response.structured } : {}), citations: citations(core.response?.structured) }; }
  async classify<L extends string>(req: AiClassifyRequest<L>): Promise<AiClassifyResult<L>> { if (!req.labels.length) throw new Error('labels are required'); const schema = { type: 'object', properties: { label: { enum: req.labels }, confidence: { type: 'number' } }, required: ['label', 'confidence'], additionalProperties: false } as const; const core = await this.invoke({ feature: req.feature, context: req.context, messages: [{ role: 'user', content: req.input }], schema, cacheEligible: false }); const value = core.response?.structured as { label?: L; confidence?: number } | undefined; return { ...this.base(core), label: value?.label ?? req.labels[0] as L, confidence: value?.confidence ?? 0, deterministic: core.route.provider === 'stub' }; }
  async translate(req: AiTranslateRequest): Promise<AiTranslateResult> { const core = await this.invoke({ feature: req.feature, context: req.context, messages: [{ role: 'user', content: req.text }], cacheEligible: false }); return { ...this.base(core), text: core.response?.text ?? '', machineGenerated: true, sourceVersion: req.sourceVersion }; }
  async summarize(req: AiSummarizeRequest): Promise<AiSummarizeResult> { const core = await this.invoke({ feature: req.feature, context: req.context, messages: [{ role: 'user', content: req.text }], cacheEligible: false }); return { ...this.base(core), text: core.response?.text ?? '', baseVersion: req.baseVersion }; }

  async embed(req: AiEmbedRequest): Promise<AiEmbedResult> {
    this.validateContext(req.context); const started = this.now(); const route = this.options.router.route(req.feature);
    if (!(await this.enabled(req.feature, req.context.orgId))) return this.embedResult(req, route, started, 'killed', code.killed);
    const provider = this.provider(route); const prompt = await this.options.prompts.get(req.feature); await this.rate(req.context, req.feature, route, prompt, started);
    if (!provider.embed) return this.embedResult(req, route, started, 'error', code.unsupported, prompt);
    let reservation: CostReservation | undefined;
    if (provider.id !== 'stub') { try { const bytes = new TextEncoder().encode(JSON.stringify({ model: route.model, inputs: req.inputs, wireOverhead: 'v1' })).byteLength; reservation = await this.options.reservations.reserve({ orgId: req.context.orgId, feature: req.feature, requestId: req.context.requestId, reservedUsd: this.options.prices.upperBound(provider.id, route.model, bytes, 1, this.retries + 1), maxOutputTokens: 1 }); } catch { return this.embedResult(req, route, started, 'error', code.reserve, prompt); } }
    const envelope: Envelope = { uncertain: false, attempts: 0 }; let vectors: readonly (readonly number[])[] = []; let dimensions = 0;
    for (let attempt = 0; attempt <= this.retries; attempt += 1) {
      if (!(await this.enabled(req.feature, req.context.orgId))) { envelope.error = new KillBeforeSend(); break; }
      envelope.attempts += 1;
      let result: Awaited<ReturnType<NonNullable<AiProviderAdapter['embed']>>>;
      try { result = await this.deadline(provider.embed(req.inputs), started); }
      catch (error) { envelope.error = error; envelope.uncertain ||= uncertain(error); if (reservation && !(error instanceof EgressBlockedError)) await this.options.reservations.addAttempt(req.context.orgId, reservation.id, attempt ? 'gateway-retry' : 'initial', route.model, null); if (error instanceof EgressBlockedError || error instanceof KillBeforeSend || this.expired(started)) break; continue; }
      vectors = result.vectors; dimensions = result.dimensions; envelope.response = { text: '', toolCalls: [], usage: result.usage, model: result.model, latencyMs: this.now() - started };
      if (reservation) await this.options.reservations.addAttempt(req.context.orgId, reservation.id, attempt ? 'gateway-retry' : 'initial', result.model, result.usage);
      break;
    }
    if (!envelope.response) { await this.closeFailed(req.context.orgId, reservation, envelope); const why = envelope.uncertain ? code.transport : reason(envelope.error); return this.embedResult(req, route, started, envelope.error instanceof KillBeforeSend ? 'killed' : envelope.error instanceof EgressBlockedError && !envelope.uncertain ? 'egress_blocked' : 'error', why, prompt, reservation, reservation && envelope.uncertain ? { usage: undefined, known: false, cost: reservation.reservedUsd } : undefined, envelope.uncertain); }
    const accounting = await this.account(req.context.orgId, provider, reservation, envelope.response, envelope.uncertain);
    if (!(await this.enabled(req.feature, req.context.orgId))) return this.embedResult(req, route, started, 'killed', code.killedResult, undefined, reservation, accounting);
    const eventId = await this.event(req.feature, req.context, { ...route, model: envelope.response.model }, prompt, 'ok', null, false, accounting.usage, reservation, accounting.known, accounting.cost, accounting.cost, started);
    return { outcome: 'ok', eventId, promptRef: prompt.ref, cacheHit: false, vectors, dimensions, model: envelope.response.model };
  }

  private async invoke(call: Invocation): Promise<Core> {
    this.validateContext(call.context); const started = this.now(); const route = this.options.router.route(call.feature);
    if (!(await this.enabled(call.feature, call.context.orgId))) return this.killed(call, route, started, code.killed);
    const provider = this.provider(route); const prompt = await this.options.prompts.get(call.feature); await this.rate(call.context, call.feature, route, prompt, started);
    let maxTokens: number; try { maxTokens = this.maxTokens(call.maxTokens ?? route.maxOutputTokens, route.maxOutputTokens); } catch { return this.error(call, route, prompt, started, code.provider); } const key = await this.cacheKey(call, route, prompt, maxTokens);
    if (key) { const cached = await this.options.cache.get(key); if (cached && await this.options.cacheBoundary.reauthorize(call.context, key) && await this.enabled(call.feature, call.context.orgId)) { const response = cached.response as AiProviderResponse; const eventId = await this.event(call.feature, call.context, { ...route, model: response.model }, prompt, 'ok', null, true, { tokensIn: 0, tokensOut: 0, tokensCached: 0 }, undefined, true, 0, 0, started); return { response, outcome: 'ok', eventId, cacheHit: true, prompt, route }; } }
    const providerInput = { system: prompt.text, messages: call.messages, ...(call.tools ? { tools: call.tools } : {}), ...(call.schema ? { schema: call.schema } : {}), maxTokens, ...(call.temperature !== undefined ? { temperature: call.temperature } : {}) };
    let reservation: CostReservation | undefined;
    if (provider.id !== 'stub') { try { reservation = await this.options.reservations.reserve({ orgId: call.context.orgId, feature: call.feature, requestId: call.context.requestId, reservedUsd: this.options.prices.upperBound(provider.id, route.model, this.estimate(provider, providerInput), maxTokens, this.retries + 1), maxOutputTokens: maxTokens }); } catch { return this.error(call, route, prompt, started, code.reserve); } }
    const envelope = await this.attempt(provider, call, prompt, route, maxTokens, reservation, started);
    if (!envelope.response) { await this.closeFailed(call.context.orgId, reservation, envelope); return envelope.error instanceof KillBeforeSend ? this.killed(call, route, started, code.killed, reservation) : this.error(call, route, prompt, started, envelope.uncertain ? code.transport : reason(envelope.error), reservation); }
    const accounting = await this.account(call.context.orgId, provider, reservation, envelope.response, envelope.uncertain);
    if (!(await this.enabled(call.feature, call.context.orgId))) return this.killed(call, route, started, code.killedResult, reservation, accounting);
    const refusal = refused(envelope.response); let response: AiProviderResponse; try { response = refusal ? envelope.response : structured(envelope.response, call.schema); } catch { return this.error(call, route, prompt, started, code.structured, reservation, accounting); }
    const eventId = await this.event(call.feature, call.context, { ...route, model: response.model }, prompt, refusal ? 'refused' : accounting.exceeded ? 'error' : 'ok', refusal ? code.refusal : accounting.exceeded ? code.exceeded : null, false, accounting.usage, reservation, accounting.known, accounting.cost, accounting.cost, started);
    if (key && !refusal && !accounting.exceeded) { try { await this.options.cache.put(key, { response, expiresAt: new Date(this.now() + 86_400_000).toISOString() }); } catch { /* never replay billed transport for cache failure */ } }
    return { ...(accounting.exceeded ? {} : { response }), outcome: refusal ? 'refused' : accounting.exceeded ? 'error' : 'ok', ...(refusal ? { reason: code.refusal, humanRoute: refusal.humanRoute } : {}), ...(accounting.exceeded ? { reason: code.exceeded } : {}), eventId, cacheHit: false, prompt, route };
  }

  private async attempt(provider: AiProviderAdapter, call: Invocation, prompt: Prompt, route: Route, maxTokens: number, reservation: CostReservation | undefined, started: number) {
    const envelope: Envelope = { uncertain: false, attempts: 0 };
    for (let attempt = 0; attempt <= this.retries; attempt += 1) {
      if (!(await this.enabled(call.feature, call.context.orgId))) { envelope.error = new KillBeforeSend(); break; }
      envelope.attempts += 1; let response: AiProviderResponse;
      try { response = await this.complete(provider, prompt, call, maxTokens, started); }
      catch (error) { envelope.error = error; envelope.uncertain ||= uncertain(error); if (reservation && !(error instanceof EgressBlockedError)) await this.options.reservations.addAttempt(call.context.orgId, reservation.id, attempt ? 'gateway-retry' : 'initial', route.model, null); if (error instanceof EgressBlockedError || this.expired(started)) break; continue; }
      envelope.response = response;
      if (reservation) await this.options.reservations.addAttempt(call.context.orgId, reservation.id, attempt ? 'gateway-retry' : 'initial', response.model, response.usage);
      break;
    }
    return envelope;
  }
  private async complete(provider: AiProviderAdapter, prompt: Prompt, call: Invocation, maxTokens: number, started: number) { const remaining = this.deadlineMs - (this.now() - started); if (remaining <= 0) throw new AmbiguousProviderTimeoutError(); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), remaining); try { return await provider.complete({ system: prompt.text, messages: call.messages, ...(call.tools ? { tools: call.tools } : {}), ...(call.schema ? { schema: call.schema } : {}), maxTokens, ...(call.temperature !== undefined ? { temperature: call.temperature } : {}), signal: controller.signal }); } finally { clearTimeout(timer); } }
  private async account(orgId: string, provider: AiProviderAdapter, reservation: CostReservation | undefined, response: AiProviderResponse, wasUncertain: boolean) { if (!reservation) return { usage: response.usage, known: true, cost: 0, exceeded: false }; const actual = this.options.prices.cost(provider.id, response.model, response.usage); const exceeded = actual > reservation.reservedUsd + 0.0000001; const cost = exceeded ? actual : wasUncertain ? reservation.reservedUsd : actual; await this.options.reservations.settle(orgId, reservation.id, cost); return { usage: wasUncertain ? undefined : response.usage, known: !wasUncertain, cost, exceeded }; }
  private async closeFailed(orgId: string, reservation: CostReservation | undefined, envelope: Envelope) { if (!reservation) return; if (envelope.uncertain) await this.options.reservations.pending(orgId, reservation.id); else await this.options.reservations.release(orgId, reservation.id); }
  private async rate(context: AiContext, feature: AiFeature, route: Route, prompt: Prompt, started: number) { const result = await this.options.rateLimiter.consume(context, feature); if (!result.allowed) { await this.event(feature, context, route, prompt, 'error', code.rate, false, undefined, undefined, false, 0, null, started); throw new AiRateLimited(result.retryAfterSeconds); } }
  private async killed(call: Invocation, route: Route, started: number, why: string, reservation?: CostReservation, accounting?: { usage: AiProviderUsage | undefined; known: boolean; cost: number }) { if (reservation && !accounting) await this.options.reservations.release(call.context.orgId, reservation.id); const eventId = await this.event(call.feature, call.context, route, undefined, 'killed', why, false, accounting?.usage, reservation, accounting?.known ?? false, accounting?.cost ?? 0, accounting ? accounting.cost : null, started); return { outcome: 'killed' as const, reason: why, humanRoute: routes[call.feature], eventId, cacheHit: false, route }; }
  private async error(call: Invocation, route: Route, prompt: Prompt, started: number, why: string, reservation?: CostReservation, accounting?: { usage: AiProviderUsage | undefined; known: boolean; cost: number }) { const eventId = await this.event(call.feature, call.context, route, prompt, why === code.egress ? 'egress_blocked' : 'error', why, false, accounting?.usage, reservation, accounting?.known ?? false, accounting?.cost ?? (reservation && uncertainCode(why) ? reservation.reservedUsd : 0), accounting ? accounting.cost : null, started); return { outcome: why === code.egress ? 'egress_blocked' as const : 'error' as const, reason: why, eventId, cacheHit: false, prompt, route }; }
  private async embedResult(req: AiEmbedRequest, route: Route, started: number, outcome: 'killed' | 'error' | 'egress_blocked', why: string, prompt?: Prompt, reservation?: CostReservation, accounting?: { usage: AiProviderUsage | undefined; known: boolean; cost: number }, pending = false) { const eventId = await this.event(req.feature, req.context, route, prompt, outcome, why, false, accounting?.usage, reservation, accounting?.known ?? false, accounting?.cost ?? 0, accounting && !pending ? accounting.cost : null, started); return { outcome, eventId, ...(outcome === 'killed' ? { humanRoute: routes[req.feature] } : { reason: why }), ...(prompt ? { promptRef: prompt.ref } : {}), cacheHit: false, vectors: [], dimensions: 0, model: route.model } as AiEmbedResult; }
  private async cacheKey(call: Invocation, route: Route, prompt: Prompt, maxTokens: number): Promise<CacheKey | null> { if (!call.cacheEligible || call.tools || call.schema || call.messages.some(message => message.role !== 'user') || !(await this.options.flags.effective('ai.cache.exact_match', call.context.orgId))) return null; const boundary = await this.options.cacheBoundary.describe(call.context, call.feature); if (!boundary.cacheable || call.context.userRole === 'caregiver') return null; const identity = JSON.stringify({ messages: call.messages.map(message => ({ role: message.role, content: message.content.trim(), toolCallId: message.toolCallId ?? null })), maxTokens, temperature: call.temperature ?? 0 }); return { orgId: call.context.orgId, locale: call.context.locale, feature: call.feature, promptVersion: prompt.ref.version, model: route.model, sourceContentVersionSet: [...boundary.sourceContentVersionSet].sort(), inputHash: createHash('sha256').update(identity).digest('hex') }; }
  private estimate(provider: AiProviderAdapter, input: Parameters<NonNullable<Estimator['estimateSerializedBytes']>>[0]) { const estimating = provider as Estimator; return estimating.estimateSerializedBytes ? estimating.estimateSerializedBytes(input) : new TextEncoder().encode(JSON.stringify({ provider: provider.id, ...input, wireOverhead: 'conservative-envelope-v1' })).byteLength; }
  private maxTokens(value: number, ceiling: number) { if (!Number.isFinite(value) || !Number.isInteger(value) || value <= 0 || value > ceiling) throw new Error('maxTokens must be a positive integer within the route ceiling'); return value; }
  private validateContext(context: AiContext) { if (!uuid.test(context.orgId) || !uuid.test(context.userId) || !context.requestId.trim()) throw new Error('explicit tenant, user and request context is required'); }
  private async enabled(feature: AiFeature, orgId: string) { return await this.options.flags.effective('ai.master', orgId) && await this.options.flags.effective(`ai.${feature}`, orgId); }
  private provider(route: Route) { const provider = this.options.providers.get(route.provider); if (!provider || provider.id !== route.provider || !provider.capabilities.sdkRetriesDisabled) throw new Error('provider configuration is invalid'); return provider; }
  private deadline<T>(promise: Promise<T>, started: number) { const remaining = this.deadlineMs - (this.now() - started); if (remaining <= 0) return Promise.reject(new AmbiguousProviderTimeoutError()); return new Promise<T>((resolve, reject) => { const timer = setTimeout(() => reject(new AmbiguousProviderTimeoutError()), remaining); promise.then(value => { clearTimeout(timer); resolve(value); }, () => { clearTimeout(timer); reject(new PossiblyBilledProviderError()); }); }); }
  private expired(started: number) { return this.now() - started >= this.deadlineMs; }
  private base(core: Core) { return { outcome: core.outcome, eventId: core.eventId, cacheHit: core.cacheHit, ...(core.prompt ? { promptRef: core.prompt.ref } : {}), ...(core.humanRoute ? { humanRoute: core.humanRoute } : {}), ...(core.reason ? { reason: core.reason } : {}) }; }
  private async event(feature: AiFeature, context: AiContext, route: Route, prompt: Prompt | undefined, outcome: AiOutcome, why: string | null, cacheHit: boolean, usage: AiProviderUsage | undefined, reservation: CostReservation | undefined, usageKnown: boolean, costUsd: number, settledUsd: number | null, started: number) { const row = await this.options.events.append({ orgId: context.orgId, requestId: context.requestId, feature, promptVersion: prompt?.ref.version ?? null, promptHash: prompt?.ref.hash ?? null, provider: route.provider, model: route.model, tokensIn: usage?.tokensIn ?? null, tokensOut: usage?.tokensOut ?? null, tokensCached: usage?.tokensCached ?? null, latencyMs: Math.max(0, this.now() - started), cacheHit, userRole: context.userRole, onBehalfOf: context.onBehalfOf ?? null, outcome, reason: why, costUsd, reservationId: reservation?.id ?? null, settledUsd, usageKnown }); return row.id; }
}

class KillBeforeSend extends Error {}
function uncertain(error: unknown) { return error instanceof PossiblyBilledProviderError || error instanceof AmbiguousProviderTimeoutError || error instanceof ProviderUsageMissingError || (error instanceof Error && error.name === 'AbortError'); }
function reason(error: unknown) { if (error instanceof KillBeforeSend) return code.killed; if (error instanceof EgressBlockedError) return code.egress; if (error instanceof AmbiguousProviderTimeoutError || (error instanceof Error && error.name === 'AbortError')) return code.timeout; if (error instanceof PossiblyBilledProviderError) return code.transport; if (error instanceof ProviderUsageMissingError) return code.usage; return code.provider; }
function uncertainCode(value: string) { return value === code.timeout || value === code.transport || value === code.usage; }
function citations(value: unknown): readonly string[] { return value && typeof value === 'object' && 'citations' in value && Array.isArray(value.citations) ? value.citations.filter((item): item is string => typeof item === 'string') : []; }
function refused(response: AiProviderResponse) { const value = response.structured; return value && typeof value === 'object' && 'outcome' in value && value.outcome === 'refused' ? { humanRoute: 'humanRoute' in value && typeof value.humanRoute === 'string' ? value.humanRoute : '/assistance' } : null; }
function structured(response: AiProviderResponse, schema: Readonly<Record<string, unknown>> | undefined) { if (!schema) return response; let value = response.structured; if (value === undefined) value = JSON.parse(response.text) as unknown; if (!valid(value, schema)) throw new Error(code.structured); return { ...response, structured: value }; }
function valid(value: unknown, schema: Readonly<Record<string, unknown>>): boolean { if (Array.isArray(schema.enum) && !schema.enum.some(item => Object.is(item, value))) return false; if (schema.type === 'number') return typeof value === 'number' && Number.isFinite(value); if (schema.type === 'string') return typeof value === 'string'; if (schema.type === 'boolean') return typeof value === 'boolean'; if (schema.type === 'array') return Array.isArray(value) && (!schema.items || typeof schema.items !== 'object' || value.every(item => valid(item, schema.items as Readonly<Record<string, unknown>>))); if (schema.type === 'object') { if (!value || typeof value !== 'object' || Array.isArray(value)) return false; const record = value as Record<string, unknown>; const properties = schema.properties && typeof schema.properties === 'object' ? schema.properties as Record<string, Readonly<Record<string, unknown>>> : {}; if (Array.isArray(schema.required) && schema.required.some(key => typeof key === 'string' && !(key in record))) return false; if (schema.additionalProperties === false && Object.keys(record).some(key => !(key in properties))) return false; return Object.entries(properties).every(([key, child]) => !(key in record) || valid(record[key], child)); } return true; }
