export const CONTRACT_VERSION = 2 as const;

export type AiFeature = 'concierge' | 'moderation' | 'translation_assist' | 'triage' | 'intake_routing' | 'event_rerank' | 'conversation_starters' | 'summaries';
export interface PromptRef { readonly feature: AiFeature; readonly version: string; readonly hash: string }
export interface AiContext { readonly orgId: string; readonly userId: string; readonly userRole: 'senior' | 'caregiver' | 'staff' | 'admin' | 'partner' | 'support'; readonly onBehalfOf?: string; readonly locale: 'en' | 'es'; readonly requestId: string }
export interface AiMessage { readonly role: 'system' | 'user' | 'assistant' | 'tool_result'; readonly content: string; readonly toolCallId?: string }
export interface AiToolSpec { readonly name: string; readonly description: string; readonly parameters: Readonly<Record<string, unknown>> }
export interface AssistanceProposal { readonly kind: 'assistance_request_proposal'; readonly category: string; readonly summary: string; readonly urgency: 'routine' | 'soon' | 'priority'; readonly proposedFields: Readonly<Record<string, unknown>>; readonly idempotencyKey: string; readonly disclaimer: string }
export interface AiToolCall { readonly id: string; readonly name: string; readonly arguments: Readonly<Record<string, unknown>> }
export type AiOutcome = 'ok' | 'refused' | 'error' | 'killed' | 'egress_blocked';
export interface AiResultBase { readonly outcome: AiOutcome; readonly promptRef?: PromptRef; readonly eventId: string; readonly humanRoute?: string; readonly reason?: string; readonly cacheHit: boolean }
export interface AiChatResult extends AiResultBase { readonly text: string; readonly toolCalls: readonly AiToolCall[]; readonly structured?: unknown; readonly citations: readonly string[] }
export interface AiClassifyResult<L extends string = string> extends AiResultBase { readonly label: L; readonly confidence: number; readonly deterministic: boolean }
export interface AiTranslateResult extends AiResultBase { readonly text: string; readonly machineGenerated: true; readonly sourceVersion: string }
export interface AiSummarizeResult extends AiResultBase { readonly text: string; readonly baseVersion: string }
export interface AiEmbedResult extends AiResultBase { readonly vectors: readonly (readonly number[])[]; readonly dimensions: number; readonly model: string }
export interface AiChatRequest { readonly feature: AiFeature; readonly context: AiContext; readonly messages: readonly AiMessage[]; readonly tools?: readonly AiToolSpec[]; readonly schema?: Readonly<Record<string, unknown>>; readonly maxTokens?: number; readonly temperature?: number }
export interface AiClassifyRequest<L extends string = string> { readonly feature: AiFeature; readonly context: AiContext; readonly input: string; readonly labels: readonly L[] }
export interface AiTranslateRequest { readonly feature: 'translation_assist'; readonly context: AiContext; readonly text: string; readonly from: 'en'; readonly to: 'es'; readonly sourceVersion: string; readonly critical: boolean }
export interface AiSummarizeRequest { readonly feature: 'summaries'; readonly context: AiContext; readonly text: string; readonly baseVersion: string }
export interface AiEmbedRequest { readonly feature: AiFeature; readonly context: AiContext; readonly inputs: readonly string[] }
export interface AiGateway { chat(req: AiChatRequest): Promise<AiChatResult>; classify<L extends string>(req: AiClassifyRequest<L>): Promise<AiClassifyResult<L>>; translate(req: AiTranslateRequest): Promise<AiTranslateResult>; summarize(req: AiSummarizeRequest): Promise<AiSummarizeResult>; embed(req: AiEmbedRequest): Promise<AiEmbedResult> }
export class AiRateLimited extends Error { constructor(readonly retryAfterSeconds: number) { super('AI rate limit exceeded'); this.name = 'AiRateLimited'; } }
export interface CacheKey { readonly orgId: string; readonly locale: AiContext['locale']; readonly feature: AiFeature; readonly promptVersion: string; readonly model: string; readonly sourceContentVersionSet: readonly string[]; readonly inputHash: string }
export interface CacheEntry { readonly key: CacheKey; readonly hitCount: number; readonly expiresAt: string; readonly cacheable: true }
export type AiProviderId = 'stub' | 'anthropic-api' | 'openai-api' | 'claude-cli-bridge' | 'codex-cli-bridge';
export interface AiProviderCapabilities { readonly tools: boolean; readonly structuredOutputs: boolean; readonly streaming: boolean; readonly embeddings: boolean; readonly batch: boolean; readonly promptCaching: boolean; readonly maxConcurrency: number; readonly timeoutMs: number; readonly samplingSchema: 'anthropic-haiku-4-5' | 'anthropic-sonnet-5' | 'anthropic-opus-5' | 'openai-chat' | 'voyage-embed' | 'stub'; readonly acceptsTemperature: boolean; readonly acceptsThinkingBudget: boolean; readonly sdkRetriesDisabled: true }
export interface GatewayRetryPolicy { readonly maxGatewayRetries: 0 | 1; readonly totalDeadlineMs: number; readonly reservationId: string }
export interface AiProviderUsage { readonly tokensIn: number; readonly tokensOut: number; readonly tokensCached: number }
export interface AiProviderResponse { readonly text: string; readonly toolCalls: readonly AiToolCall[]; readonly structured?: unknown; readonly usage: AiProviderUsage; readonly model: string; readonly latencyMs: number }
export interface AiProviderAdapter { readonly id: AiProviderId; readonly capabilities: AiProviderCapabilities; complete(input: { readonly system: string; readonly messages: readonly AiMessage[]; readonly tools?: readonly AiToolSpec[]; readonly schema?: Readonly<Record<string, unknown>>; readonly maxTokens?: number; readonly temperature?: number; readonly signal: AbortSignal }): Promise<AiProviderResponse>; embed?(inputs: readonly string[]): Promise<{ readonly vectors: readonly (readonly number[])[]; readonly dimensions: number; readonly model: string; readonly usage: AiProviderUsage }> }
export interface AiEvent { readonly id: string; readonly orgId: string; readonly requestId: string; readonly feature: AiFeature; readonly promptVersion: string | null; readonly promptHash: string | null; readonly provider: AiProviderId; readonly model: string; readonly tokensIn: number | null; readonly tokensOut: number | null; readonly tokensCached: number | null; readonly latencyMs: number; readonly cacheHit: boolean; readonly userRole: AiContext['userRole']; readonly onBehalfOf: string | null; readonly outcome: AiOutcome; readonly reason: string | null; readonly costUsd: number; readonly reservationId: string | null; readonly settledUsd: number | null; readonly usageKnown: boolean; readonly createdAt: string }
export type CostReservationState = 'held' | 'settled' | 'released' | 'pending_reconciliation' | 'expired';
export interface CostReservation { readonly id: string; readonly orgId: string; readonly feature: AiFeature; readonly requestId: string; readonly reservedUsd: number; readonly maxOutputTokens: number; readonly state: CostReservationState; readonly createdAt: string; readonly closedAt: string | null; readonly settledUsd: number | null; readonly attempts: readonly { readonly kind: 'initial' | 'gateway-retry' | 'tool-round' | 'fallback' | 'judge'; readonly model: string; readonly startedAt: string; readonly usage: AiProviderUsage | null }[] }
