/* eslint-disable @typescript-eslint/unbound-method -- repository methods are Vitest spies in this isolated service test */
import { describe,expect,it,vi } from 'vitest';
import { AdminForbidden,AdminInvalid,QueueContractError,createAdminService,loadQueue,queueDefinitions,type AdminRepository,type ContentPageInput,type PartnerInput,type QueueKind } from '../../../packages/admin/src/index.ts';
const actor={id:'00000000-0000-4000-8000-000000000019',orgId:'10000000-0000-4000-8000-000000000019',roles:['staff']};
const empty={items:[],meta:{next_cursor:null,total_known:true}};
const repository:AdminRepository={listUsers:vi.fn(()=>Promise.resolve(empty)),findUser:vi.fn(()=>Promise.resolve({id:actor.id,org_id:actor.orgId,display_name:'Admin',roles:['admin'],account_state:'active' as const,version:1})),updateUser:vi.fn(()=>Promise.resolve(null)),listContentPages:vi.fn(()=>Promise.resolve(empty)),createContentPage:vi.fn((_o:string,_a:string,input:ContentPageInput)=>Promise.resolve({id:actor.id,slug:input.slug,version:1,critical:false})),listFaqs:vi.fn(()=>Promise.resolve(empty)),createFaq:vi.fn((_o,_a,input)=>Promise.resolve({id:actor.id,...input,version:1})),listAnnouncements:vi.fn(()=>Promise.resolve(empty)),createAnnouncement:vi.fn((_o,_a,input)=>Promise.resolve({id:actor.id,...input,version:1})),listPartners:vi.fn(()=>Promise.resolve(empty)),createPartner:vi.fn((_o:string,_a:string,input:PartnerInput)=>Promise.resolve({id:actor.id,name:input.name,categories:input.categories??[],contact:input.contact,version:1})),analytics:vi.fn(()=>Promise.resolve({tiles:[],as_of:new Date(0).toISOString(),source_version:'test'}))};
const ids={assistance:'00000000-0000-4000-8000-000000000011',rides:'00000000-0000-4000-8000-000000000012',moderation:'00000000-0000-4000-8000-000000000013',translation:'00000000-0000-4000-8000-000000000014'};
const valid:Record<QueueKind,unknown>={assistance:{items:[{id:ids.assistance,org_id:actor.orgId,state:'pending_unowned',owner_id:actor.id,sla_due_at:'2026-09-11T12:30:00Z'}],meta:{}},rides:{items:[{id:ids.rides,org_id:actor.orgId,state:'waiting_for_dispatcher',pickup_at:'2026-09-11T12:30:00-04:00',confirmed_at:null}],meta:{}},moderation:{items:[{id:ids.moderation,source:'user_report',target_type:'post',decision:null,decided_by:null}],meta:{}},translation:{items:[{id:ids.translation,key:'home.title',locale:'es',source_version:'v1',status:'awaiting_review'}],meta:{}}};
describe('WP-019 admin service',()=>{
  it('fails closed for a resident and does not touch storage',async()=>{const service=createAdminService(repository);await expect(service.listUsers({...actor,roles:['senior']})).rejects.toBeInstanceOf(AdminForbidden);expect(vi.mocked(repository.listUsers)).not.toHaveBeenCalled();});
  it('prevents self-hold and non-reversible states',async()=>{const service=createAdminService(repository);await expect(service.updateUser(actor,actor.id,{account_state:'held_for_review',expected_version:1})).rejects.toBeInstanceOf(AdminInvalid);await expect(service.updateUser(actor,'20000000-0000-4000-8000-000000000019',{account_state:'deactivated' as never,expected_version:1})).rejects.toBeInstanceOf(AdminInvalid);});
  it('uses one adapter and exact endpoints for all four locked page types',async()=>{const get=vi.fn((endpoint:string)=>{const kind=(Object.keys(queueDefinitions) as QueueKind[]).find(candidate=>queueDefinitions[candidate].endpoint===endpoint);if(!kind)throw new Error('unexpected endpoint');return Promise.resolve(valid[kind]);});for(const kind of Object.keys(queueDefinitions) as QueueKind[]){const result=await loadQueue({get},kind);expect(result.items[0]?.queue).toBe(kind);}expect(get.mock.calls.map(call=>call[0])).toEqual(Object.values(queueDefinitions).map(item=>item.endpoint));});
  it.each(Object.keys(queueDefinitions) as QueueKind[])('fails visibly when the %s queue drifts from its contract',async kind=>{await expect(loadQueue({get:()=>Promise.resolve({items:[{}],meta:{}})},kind)).rejects.toBeInstanceOf(QueueContractError);});
  it.each([
    ['assistance',{id:ids.assistance,org_id:actor.orgId,state:'pending_unowned',sla_due_at:'2026-02-30T12:00:00Z'}],
    ['rides',{id:ids.rides,org_id:actor.orgId,state:'waiting_for_dispatcher',pickup_at:'not-a-date'}],
    ['moderation',{id:ids.moderation,source:'user_report',target_type:'post',decision:null,decided_by:'not-a-uuid'}],
    ['translation',{id:'not-a-uuid',key:'home.title',locale:'es',source_version:'v1',status:'awaiting_review'}],
  ] as const)('rejects malformed OpenAPI formats in the %s queue',async(kind,item)=>{await expect(loadQueue({get:()=>Promise.resolve({items:[item],meta:{}})},kind)).rejects.toBeInstanceOf(QueueContractError);});
});
