#!/usr/bin/env node
/** Bring a builder lane or reserved ss-n0 stack up, down, or back to seed. */
import { spawn, spawnSync } from 'node:child_process';
import { createHash, randomUUID } from 'node:crypto';
import { closeSync, existsSync, openSync, readFileSync, realpathSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_PATH = fileURLToPath(import.meta.url);
const REPO_ROOT = resolve(dirname(SCRIPT_PATH), '..');
const COMPOSE_FILE = join(REPO_ROOT, 'infra', 'docker-compose.yml');
const DEMO_ORG_ID = '11111111-1111-4111-8111-111111111111';
const LOCAL_DEMO_ASSISTANCE_ENCRYPTION_KEY = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=';
const DEMO_WEB_CHILD = '__demo-web-child';
const AGENT_ENV = [
  'AI_AGENT', 'CURSOR_TRACE_ID', 'CURSOR_AGENT', 'CURSOR_EXTENSION_HOST_ROLE', 'GEMINI_CLI',
  'CODEX_SANDBOX', 'CODEX_CI', 'CODEX_THREAD_ID', 'ANTIGRAVITY_AGENT', 'AUGMENT_AGENT',
  'OPENCODE_CLIENT', 'CLAUDECODE', 'CLAUDE_CODE', 'CLAUDE_CODE_IS_COWORK', 'REPL_ID',
  'COPILOT_MODEL', 'COPILOT_ALLOW_ALL', 'COPILOT_GITHUB_TOKEN',
];

function fail(message) { throw new Error(message); }

export function parseFlags(argv) {
  const flags = { demo: false, mode: 'hybrid', lane: null, slot: null, profiles: [] };
  for (let i = 1; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--demo') flags.demo = true;
    else if (arg === '--lane') flags.lane = Number(argv[++i]);
    else if (arg === '--slot') flags.slot = Number(argv[++i]);
    else if (arg === '--mode') flags.mode = argv[++i];
    else if (arg === '--profile') flags.profiles.push(argv[++i]);
    else fail(`unknown option ${arg}`);
  }
  if (!['hybrid', 'full-docker'].includes(flags.mode)) fail('--mode must be hybrid or full-docker.');
  return { command: argv[0], flags };
}

export function demoWebStatePath(repoRoot = REPO_ROOT) {
  const canonical = realpathSync.native(repoRoot).toLowerCase();
  const key = createHash('sha256').update(`${canonical}\0ss-n0`).digest('hex').slice(0, 20);
  return join(tmpdir(), `seniorsocial-demo-web-${key}.json`);
}

function playwrightVersion() {
  const pkg = JSON.parse(readFileSync(join(REPO_ROOT, 'package.json'), 'utf8'));
  const spec = pkg.devDependencies?.['@playwright/test'];
  if (!spec) fail('@playwright/test is not in package.json; cannot derive PLAYWRIGHT_VERSION.');
  if (!/^\d+\.\d+\.\d+$/.test(spec)) fail(`@playwright/test is "${spec}", not an exact version. Pin it.`);
  return spec;
}

function laneEnv(flags) {
  if (flags.demo) {
    if (flags.slot !== null && flags.slot !== 0) fail('the demo stack is slot 0 only.');
    return { LANE: '0', COMPOSE_PROJECT_NAME: 'ss-n0', WEB_PORT: '3100', DB_PORT: '5532', MAILPIT_SMTP_PORT: '1125', MAILPIT_UI_PORT: '8125', ADMINER_PORT: '8180', PLAYWRIGHT_VERSION: playwrightVersion(), __envFile: 'infra/.env.demo0' };
  }
  const n = flags.lane;
  if (n === null || Number.isNaN(n)) fail('--lane <1..4> is required. There is no default lane.');
  if (n === 0) fail('lane 0 is reserved for ss-n0. Use --demo.');
  if (n < 1 || n > 4) fail('--lane must be 1, 2, 3 or 4.');
  const base = 10 * n;
  return { LANE: String(n), COMPOSE_PROJECT_NAME: `ss-lane${n}`, WEB_PORT: String(3000 + base), DB_PORT: String(5432 + base), MAILPIT_SMTP_PORT: String(1025 + base), MAILPIT_UI_PORT: String(8025 + base), ADMINER_PORT: String(8080 + base), PLAYWRIGHT_VERSION: playwrightVersion(), __envFile: `infra/.env.lane${n}` };
}

function writeEnvFile(env) {
  const path = join(REPO_ROOT, env.__envFile);
  const body = Object.entries(env).filter(([key]) => !key.startsWith('__')).map(([key, value]) => `${key}=${value}`).join('\n');
  writeFileSync(path, `# Generated by scripts/lane-launch.mjs. Do not edit by hand.\n\n${body}\n`, 'utf8');
  return path;
}

function compose(env, flags, args) {
  const full = ['compose', '-f', COMPOSE_FILE, '--env-file', join(REPO_ROOT, env.__envFile), ...flags.profiles.flatMap(profile => ['--profile', profile]), ...args];
  console.log(`lane-launch: docker ${full.join(' ')}`);
  const result = spawnSync('docker', full, { cwd: REPO_ROOT, stdio: 'inherit', env: { ...process.env, ...env } });
  return result.status === null ? 1 : result.status;
}

function pnpmInvocation(args) {
  if (process.platform !== 'win32') return { executable: 'pnpm', args };
  const corepackPnpm = join(dirname(process.execPath), 'node_modules', 'corepack', 'dist', 'pnpm.js');
  if (!existsSync(corepackPnpm)) fail('the pnpm Corepack entry point beside Node is missing.');
  return { executable: process.execPath, args: [corepackPnpm, ...args] };
}

function runHost(env, args) {
  console.log(`lane-launch: pnpm ${args.join(' ')}`);
  const command = pnpmInvocation(args);
  const result = spawnSync(command.executable, command.args, { cwd: REPO_ROOT, stdio: 'inherit', env: { ...process.env, ...env } });
  return result.status === null ? 1 : result.status;
}

export function demoWebEnvironment(env, inherited = process.env) {
  const child = { ...inherited };
  for (const name of AGENT_ENV) delete child[name];
  const db = inherited.POSTGRES_DB ?? 'seniorsocial';
  const password = inherited.SENIORSOCIAL_RUNTIME_DB_PASSWORD ?? 'ss_runtime_dev_only';
  return { ...child, NODE_ENV: 'development', DATABASE_URL: `postgres://seniorsocial_runtime:${encodeURIComponent(password)}@127.0.0.1:${env.DB_PORT}/${encodeURIComponent(db)}`, DATABASE_SSL: inherited.DATABASE_SSL ?? 'disable', FIELD_ENCRYPTION_KEY: inherited.FIELD_ENCRYPTION_KEY ?? '0'.repeat(64), ASSISTANCE_ENCRYPTION_KEY: inherited.ASSISTANCE_ENCRYPTION_KEY ?? LOCAL_DEMO_ASSISTANCE_ENCRYPTION_KEY, AUTH_TOKEN_PEPPER: inherited.AUTH_TOKEN_PEPPER ?? 'local-development-auth-pepper', AUTH_SIMULATION_EXPOSE_CREDENTIALS: 'true', SENIORSOCIAL_ORG_ID: inherited.SENIORSOCIAL_ORG_ID ?? DEMO_ORG_ID, AI_PROVIDER: inherited.AI_PROVIDER ?? 'stub', SMS_PROVIDER: 'simulator', EMAIL_PROVIDER: 'mailpit', SMTP_HOST: '127.0.0.1', SMTP_PORT: env.MAILPIT_SMTP_PORT, PORT: env.WEB_PORT, HOSTNAME: '127.0.0.1' };
}

export function demoMaintenanceEnvironment(env, inherited = process.env) {
  const user = inherited.POSTGRES_USER ?? 'ss';
  const password = inherited.POSTGRES_PASSWORD ?? 'ss_dev_only';
  const db = inherited.POSTGRES_DB ?? 'seniorsocial';
  return {
    DATABASE_URL: `postgres://${encodeURIComponent(user)}:${encodeURIComponent(password)}@localhost:${env.DB_PORT}/${encodeURIComponent(db)}`,
    DATABASE_SSL: inherited.DATABASE_SSL ?? 'disable',
    AUTH_TOKEN_PEPPER: inherited.AUTH_TOKEN_PEPPER ?? 'local-development-auth-pepper',
    ASSISTANCE_ENCRYPTION_KEY: inherited.ASSISTANCE_ENCRYPTION_KEY ?? LOCAL_DEMO_ASSISTANCE_ENCRYPTION_KEY,
  };
}

export function demoWebCommand(port = '3100') {
  return ['--filter', '@seniorsocial/web', 'exec', 'next', 'dev', '--hostname', '127.0.0.1', '--port', port];
}

const normalized = value => value.replaceAll('\\', '/').replaceAll('"', '').toLowerCase();
export function commandMatchesDemoWeb(commandLine, token, scriptPath = SCRIPT_PATH) {
  if (!commandLine || !token) return false;
  const actual = normalized(commandLine);
  return actual.includes(normalized(scriptPath)) && actual.includes(DEMO_WEB_CHILD) && actual.includes(token.toLowerCase());
}

function processCommandLine(pid) {
  if (!Number.isSafeInteger(pid) || pid <= 0) return null;
  if (process.platform === 'win32') {
    const result = spawnSync('powershell.exe', ['-NoProfile', '-NonInteractive', '-Command', `(Get-CimInstance Win32_Process -Filter 'ProcessId = ${pid}').CommandLine`], { encoding: 'utf8', windowsHide: true });
    return result.status === 0 ? result.stdout.trim() || null : null;
  }
  try { return readFileSync(`/proc/${pid}/cmdline`, 'utf8').replaceAll('\0', ' '); } catch { return null; }
}

function readState(statePath) {
  try {
    const state = JSON.parse(readFileSync(statePath, 'utf8'));
    if (state.schemaVersion !== 1 || state.repoRoot !== realpathSync.native(REPO_ROOT) || state.project !== 'ss-n0' || !Number.isSafeInteger(state.pid) || typeof state.token !== 'string') return null;
    return state;
  } catch { return null; }
}

const delay = milliseconds => new Promise(done => setTimeout(done, milliseconds));
function removeDemoWebArtifacts(statePath) {
  rmSync(statePath, { force: true });
  rmSync(`${statePath}.log`, { force: true });
}
async function healthReady(url) {
  try {
    const response = await fetch(url, { signal: AbortSignal.timeout(2_000), cache: 'no-store' });
    if (!response.ok) return false;
    const body = await response.json();
    return body?.status === 'ok' && body?.service === 'web';
  } catch { return false; }
}

async function stopDemoWeb() {
  const statePath = demoWebStatePath();
  const state = readState(statePath);
  if (!state) { removeDemoWebArtifacts(statePath); return { stopped: false, reason: 'no-owned-process' }; }
  if (!commandMatchesDemoWeb(processCommandLine(state.pid), state.token)) {
    removeDemoWebArtifacts(statePath);
    console.warn('lane-launch: stale demo web state removed; the observed PID was not touched.');
    return { stopped: false, reason: 'identity-mismatch' };
  }
  if (process.platform === 'win32') spawnSync('taskkill.exe', ['/PID', String(state.pid), '/T', '/F'], { stdio: 'ignore', windowsHide: true });
  else {
    try { process.kill(-state.pid, 'SIGTERM'); } catch { /* already stopped */ }
    for (let count = 0; count < 20 && processCommandLine(state.pid); count += 1) await delay(100);
    if (processCommandLine(state.pid)) { try { process.kill(-state.pid, 'SIGKILL'); } catch { /* already stopped */ } }
  }
  if (commandMatchesDemoWeb(processCommandLine(state.pid), state.token)) {
    console.error(`lane-launch: owned ss-n0 host web supervisor PID ${state.pid} could not be stopped.`);
    return { stopped: false, reason: 'stop-failed' };
  }
  removeDemoWebArtifacts(statePath);
  console.log(`lane-launch: stopped owned ss-n0 host web supervisor PID ${state.pid}.`);
  return { stopped: true, reason: 'stopped' };
}

async function startDemoWeb(env) {
  const statePath = demoWebStatePath();
  const healthUrl = `http://127.0.0.1:${env.WEB_PORT}/api/v1/health`;
  const existing = readState(statePath);
  if (existing && commandMatchesDemoWeb(processCommandLine(existing.pid), existing.token)) {
    if (await healthReady(healthUrl)) { console.log(`lane-launch: owned ss-n0 host web is already healthy (PID ${existing.pid}).`); return 0; }
    const stopped = await stopDemoWeb();
    if (stopped.reason === 'stop-failed') return 1;
  } else if (existsSync(statePath)) {
    removeDemoWebArtifacts(statePath);
    console.warn('lane-launch: stale demo web state removed; no process was stopped.');
  }
  if (await healthReady(healthUrl)) {
    console.error(`lane-launch: ${healthUrl} is already served by an unowned process; it was not touched.`);
    return 1;
  }

  const token = randomUUID();
  const logPath = `${statePath}.log`;
  const logFd = openSync(logPath, 'a');
  const child = spawn(process.execPath, [SCRIPT_PATH, DEMO_WEB_CHILD, token, env.WEB_PORT], { cwd: REPO_ROOT, detached: true, windowsHide: true, env: demoWebEnvironment(env), stdio: ['ignore', logFd, logFd] });
  closeSync(logFd);
  if (!child.pid) return 1;
  child.unref();
  const state = { schemaVersion: 1, repoRoot: realpathSync.native(REPO_ROOT), project: 'ss-n0', pid: child.pid, token, healthUrl, logPath };
  const temporary = `${statePath}.${process.pid}.tmp`;
  writeFileSync(temporary, `${JSON.stringify(state)}\n`, { encoding: 'utf8', mode: 0o600 });
  renameSync(temporary, statePath);
  for (let attempt = 0; attempt < 60; attempt += 1) {
    if (!commandMatchesDemoWeb(processCommandLine(child.pid), token)) break;
    if (await healthReady(healthUrl)) { console.log(`lane-launch: ss-n0 host web healthy at ${healthUrl} (PID ${child.pid}).`); return 0; }
    await delay(1_000);
  }
  console.error(`lane-launch: ss-n0 host web did not become healthy; diagnostics are in ${logPath}.`);
  await stopDemoWeb();
  return 1;
}

function runDemoWebChild(port) {
  const command = pnpmInvocation(demoWebCommand(port));
  const result = spawnSync(command.executable, command.args, { cwd: REPO_ROOT, stdio: 'inherit', env: process.env });
  return result.status === null ? 1 : result.status;
}

async function main(argv) {
  if (argv[0] === DEMO_WEB_CHILD) return runDemoWebChild(argv[2]);
  const { command, flags } = parseFlags(argv);
  if (!existsSync(COMPOSE_FILE)) fail(`${COMPOSE_FILE} is missing.`);
  const env = laneEnv(flags);
  if (command === 'demo-reset' && !flags.demo) fail('demo-reset is reserved for the demo stack. Use --demo --slot 0.');
  const envPath = writeEnvFile(env);
  console.log(`lane-launch: ${env.COMPOSE_PROJECT_NAME} -> web ${env.WEB_PORT}, db ${env.DB_PORT}, mailpit ${env.MAILPIT_UI_PORT}`);
  console.log(`lane-launch: wrote ${envPath}`);
  let status = 0;
  switch (command) {
    case 'up': {
      if (flags.demo && flags.mode === 'full-docker') {
        const web = await stopDemoWeb();
        if (web.reason === 'stop-failed') { status = 1; break; }
      }
      const services = flags.mode === 'full-docker' ? [] : ['db', 'worker', 'mailpit'];
      const build = flags.mode === 'full-docker' ? ['--build'] : [];
      status = compose(env, flags, ['up', '-d', ...build, ...services]);
      if (status === 0 && flags.demo && flags.mode !== 'full-docker') status = await startDemoWeb(env);
      if (status !== 0 && flags.demo) { await stopDemoWeb(); compose(env, flags, ['down', '--remove-orphans']); break; }
      if (status === 0) {
        console.log(`lane-launch: web        http://localhost:${env.WEB_PORT}`);
        console.log(`lane-launch: mailpit UI http://localhost:${env.MAILPIT_UI_PORT}`);
        if (!flags.demo && flags.mode !== 'full-docker') console.log('lane-launch: hybrid mode - run `pnpm --filter @seniorsocial/web dev` on the host for `web`.');
      }
      break;
    }
    case 'down': {
      const web = flags.demo ? await stopDemoWeb() : { stopped: false };
      status = compose(env, flags, ['down', '--remove-orphans']);
      if (web.reason === 'stop-failed') status = 1;
      if (status === 0 && flags.demo && !web.stopped) console.log('lane-launch: no owned ss-n0 host web process was running.');
      break;
    }
    case 'db-reset':
    case 'demo-reset': {
      status = compose(env, flags, ['down', '-v', '--remove-orphans']);
      if (status === 0) status = compose(env, flags, ['up', '-d', '--wait', 'db']);
      if (status !== 0) break;
      if (command === 'demo-reset') {
        const maintenance = demoMaintenanceEnvironment(env);
        status = runHost(maintenance, ['db:migrate']);
        if (status === 0) status = runHost(maintenance, ['db:seed']);
        if (status === 0) status = runHost(maintenance, ['exec', 'tsx', 'packages/db/seed/demo/run.ts']);
        if (status === 0) console.log('lane-launch: deterministic WP-034 demo state restored.');
      } else console.log('lane-launch: db volume recreated. Run `pnpm db:migrate` then `pnpm db:seed`.');
      break;
    }
    case 'ports': break;
    default: fail('usage: lane-launch.mjs <up|down|db-reset|demo-reset|ports> [--lane 1..4 | --demo] [--mode hybrid|full-docker] [--profile <name>]');
  }
  return status;
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(SCRIPT_PATH)) {
  main(process.argv.slice(2)).then(status => { process.exitCode = status; }).catch(error => {
    console.error(`lane-launch: ${error instanceof Error ? error.message : String(error)}`);
    process.exitCode = 1;
  });
}
