import type {SessionRecord} from '@seniorsocial/auth';
import {createDatabaseClient} from '@seniorsocial/db';
import {readCookie,SESSION_COOKIE,withAuthService} from '../../../../(auth)/auth/_shared';
import {IndividualExportFault,type ExportActor,type IndividualExportRequest} from '../../../../../../../packages/individual-exports/src/index.ts';
import {EnvironmentExportKeys,PostgresIndividualAuthority,PostgresIndividualSnapshot,ReportingForbidden,ReportingUnavailable,createIndividualGateway,reauthorizeIndividual,type IndividualApiArtifact,type IndividualApiJob,type ReportingActor} from '../../../../../../../packages/reporting/src/index.ts';
export interface IndividualRouteGateway{create(actor:ExportActor,request:IndividualExportRequest,key:string):Promise<IndividualApiJob>;get(actor:ExportActor,id:string):Promise<IndividualApiJob|null>;download(actor:ExportActor,id:string,accept:string|null):Promise<IndividualApiArtifact|null>}
export async function exportContext(request:Request):Promise<ReportingActor>{const orgId=process.env.SENIORSOCIAL_ORG_ID;if(!orgId)throw new ReportingUnavailable('export identity unavailable');const token=readCookie(request,SESSION_COOKIE);if(!token)throw new ReportingForbidden('authenticated session required');let session:SessionRecord|null;try{session=await withAuthService(orgId,service=>service.session(orgId,token));}catch{throw new ReportingUnavailable('authentication service unavailable');}if(!session||session.orgId!==orgId)throw new IndividualExportFault(404,'export_unavailable','export unavailable');return{id:session.userId,orgId:session.orgId,roles:session.roles};}
export const exportActor=(actor:ReportingActor):ExportActor=>({orgId:actor.orgId,userId:actor.id,roles:actor.roles.filter((role):role is ExportActor['roles'][number]=>['senior','caregiver','staff','admin','support','partner'].includes(role))});
let gateway:IndividualRouteGateway|undefined;
export function individualRuntime():IndividualRouteGateway{if(gateway)return gateway;try{const client=createDatabaseClient();gateway=createIndividualGateway({client,authority:new PostgresIndividualAuthority(client),snapshots:new PostgresIndividualSnapshot(client),keys:new EnvironmentExportKeys(),reauthorize:reauthorizeIndividual});return gateway;}catch{throw new ReportingUnavailable('individual export production adapters are unavailable');}}
export function individualProblem(error:unknown):Response|null{if(!(error instanceof IndividualExportFault))return null;const status=error.code==='format_mismatch'?406:error.status;const title=status===404?'Not Found':status===406?'Not Acceptable':status===409?'Conflict':status===410?'Gone':'Unprocessable Entity';return Response.json({type:'about:blank',title,status},{status,headers:{'cache-control':'no-store','content-type':'application/problem+json'}});}
