import { describe,expect,it,vi } from 'vitest';
import { createForums,type Block,type ForumIdentity,type ForumPost,type ForumRepository,type ModerationItem } from '../../../packages/forums/src/index.ts';

const identity:ForumIdentity={orgId:'11111111-1111-4111-8111-111111111111',userId:'22222222-2222-4222-8222-222222222222',roles:['senior'],locale:'en',requestId:'request-1'};
const post:ForumPost={id:'33333333-3333-4333-8333-333333333333',author_id:identity.userId,body:'Coffee at ten?',flag_state:'none'};
function repository(overrides:Partial<ForumRepository>={}):ForumRepository{return {
  listTopics:vi.fn(async()=>({items:[],meta:{next_cursor:null,total_known:true as const}})),listPosts:vi.fn(async()=>({items:[post],meta:{next_cursor:null,total_known:true as const}})),
  createPost:vi.fn(async()=>({...post})),createReply:vi.fn(async()=>({id:'44444444-4444-4444-8444-444444444444',body:'Yes'})),
  reportPost:vi.fn(async()=>({id:'55555555-5555-4555-8555-555555555555',state:'open' as const})),listBlocks:vi.fn(async()=>[]),
  block:vi.fn(async(_,userId)=>({user_id:userId,created_at:new Date(0).toISOString()} as Block)),
  listModeration:vi.fn(async()=>({items:[],meta:{next_cursor:null,total_known:true as const}})),decide:vi.fn(async()=>null),flag:vi.fn(async()=>true),...overrides};}

describe('WP-015 forum invariants',()=>{
  it('makes zero classifier calls while moderation is disabled and still posts',async()=>{const repo=repository();const classify=vi.fn();const service=createForums(repo,{enabled:vi.fn(async()=>false),classify});expect(await service.createPost(identity,'66666666-6666-4666-8666-666666666666',{body:' Hello '})).toMatchObject({body:'Coffee at ten?',flag_state:'none'});expect(classify).not.toHaveBeenCalled();});
  it('returns the committed post when the flag store fails instead of inviting a duplicate retry',async()=>{const repo=repository();const service=createForums(repo,{enabled:vi.fn(async()=>{throw new Error('flag store down');}),classify:vi.fn()});expect(await service.createPost(identity,'66666666-6666-4666-8666-666666666666',{body:'Hello'})).toMatchObject({id:post.id,flag_state:'none'});});
  it('does not claim a queued flag when a concurrent flag persistence loses the race',async()=>{const repo=repository({flag:vi.fn(async()=>false)});const service=createForums(repo,{enabled:vi.fn(async()=>true),classify:vi.fn(async()=>({outcome:'ok' as const,label:'review' as const,eventId:'77777777-7777-4777-8777-777777777777'}))});expect(await service.createPost(identity,'66666666-6666-4666-8666-666666666666',{body:'Hello'})).toMatchObject({flag_state:'none'});});
  it('queues an advisory AI flag without hiding or rewriting content',async()=>{const repo=repository();const service=createForums(repo,{enabled:vi.fn(async()=>true),classify:vi.fn(async input=>{expect(input.content).toBe('Hello');return {outcome:'ok' as const,label:'review' as const,eventId:'77777777-7777-4777-8777-777777777777',promptVersion:'v1'};})});const result=await service.createPost(identity,'66666666-6666-4666-8666-666666666666',{body:'Hello'});expect(result).toMatchObject({body:'Coffee at ten?',flag_state:'flagged_awaiting_human'});expect(repo.flag).toHaveBeenCalledOnce();});
  it.each(['refused','error','killed','egress_blocked'] as const)('keeps content visible on %s classifier outcome',async outcome=>{const repo=repository();const service=createForums(repo,{enabled:vi.fn(async()=>true),classify:vi.fn(async()=>({outcome,label:'review' as const,eventId:'77777777-7777-4777-8777-777777777777'}))});expect(await service.createPost(identity,'66666666-6666-4666-8666-666666666666',{body:'Hello'})).toMatchObject({flag_state:'none'});expect(repo.flag).not.toHaveBeenCalled();});
  it('rejects self-blocks, overlong content, malformed paging, and rate-limited writes',async()=>{const repo=repository();const limited=createForums(repo,undefined,{consume:vi.fn(async()=>({allowed:false,retryAfterSeconds:7}))});expect(await limited.block(identity,{user_id:identity.userId})).toMatchObject({status:422,code:'cannot_block_self'});expect(await limited.createPost(identity,'66666666-6666-4666-8666-666666666666',{body:'x'.repeat(8001)})).toMatchObject({status:422});expect(await limited.listTopics(identity,{limit:101})).toMatchObject({status:404});expect(await limited.createReply(identity,post.id,{body:'reply'})).toMatchObject({status:429,retry_after:7});});
  it('allows only staff/admin humans to see and decide the queue',async()=>{const item:ModerationItem={id:'88888888-8888-4888-8888-888888888888',source:'user_report',target_type:'post',target_id:post.id,decision:null,decided_by:null};const repo=repository({decide:vi.fn(async()=>({...item,decision:'remove' as const,decided_by:'99999999-9999-4999-8999-999999999999'}))});const service=createForums(repo);expect(await service.listModeration(identity)).toMatchObject({status:403});const staff={...identity,userId:'99999999-9999-4999-8999-999999999999',roles:['staff'] as const};expect(await service.decide(staff,item.id,{decision:'remove',reason:'Rule S-1 scam pattern'})).toMatchObject({decision:'remove'});expect(await service.decide(staff,item.id,{decision:'remove',reason:'line one\nline two'})).toMatchObject({status:422});});
  it('preserves the locked message-review shape without exposing native report text',async()=>{const message:ModerationItem={id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',source:'user_report',target_type:'message',target_id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',decision:null,decided_by:null};const repo=repository({listModeration:vi.fn(async()=>({items:[message],meta:{next_cursor:null,total_known:true as const}}))});const staff={...identity,roles:['staff'] as const};const result=await createForums(repo).listModeration(staff);expect(result).toEqual({items:[message],meta:{next_cursor:null,total_known:true}});expect(Object.keys(message).sort()).toEqual(['decided_by','decision','id','source','target_id','target_type']);});
});
